import test from 'node:test';import assert from 'node:assert/strict';import {BufferGate} from './resource-io.ts';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {MusicService} from '../service/service.ts';import {testResources} from '../service/resources/testing.ts';import {serveHttp} from './http.ts';
const deferred=()=>{let resolve!:()=>void;const promise=new Promise<void>(r=>resolve=r);return {resolve,promise};};
test('response buffers are bounded, queued reads cancel without consuming a slot, overflow is explicit',async()=>{
 const gate=new BufferGate(1,1),hold=deferred(),entered=deferred();let starts=0;const first=gate.run(new AbortController().signal,async()=>{entered.resolve();await hold.promise;});await entered.promise;const controller=new AbortController(),next=gate.run(controller.signal,async()=>{starts++;}),cancelled=assert.rejects(next);await assert.rejects(gate.run(new AbortController().signal,async()=>{}),{code:'IO_BUSY'});controller.abort();await cancelled;assert.equal(starts,0);hold.resolve();await first;await gate.run(new AbortController().signal,async()=>{starts++;});assert.equal(starts,1);
});
test('large upload waits before buffering, resource cancellation saves nothing and playback is independent',async()=>{
 const root=await mkdtemp(join(tmpdir(),'upload-resource-')),resources=testResources(),hold=deferred(),entered=deferred(),service=await MusicService.open(root,()=>{throw Error('unused');},async()=>new Uint8Array(),false,undefined,{installed:()=>true,prepare:async()=>{},generate:async()=>{throw Error('unused');}},undefined,resources),http=await serveHttp(service,{read:async()=>new Uint8Array(),has:()=>false,embedded:false});resources.register('hold',{resident:()=>undefined,unload:async()=>{}});const blocking=resources.run({id:'hold',engine:'hold',demand:resources.estimate('hold',{}),execute:async()=>{entered.resolve();await hold.promise;}});await entered.promise;
 try{const wav=await readFile('public/tts-presets/official.wav'),voice=service.speech.addVoice('原音',wav);const upload=fetch(http.runtime.url+`/conversion/upload?voiceId=${voice.id}&name=audio.wav&requestId=test`,{method:'POST',headers:{authorization:`Bearer ${http.runtime.token}`},body:wav});for(let i=0;i<100&&!resources.snapshot().queued.some(t=>t.engine==='import');i++)await new Promise(r=>setTimeout(r,5));const task=resources.snapshot().queued.find(t=>t.engine==='import');assert.ok(task);assert.equal(service.conversion.snapshot().jobs.length,0);const playback=await fetch(http.runtime.url+`/speech/voice-audio/${voice.id}`,{headers:{authorization:`Bearer ${http.runtime.token}`}});assert.equal(playback.status,200);assert.equal((await playback.arrayBuffer()).byteLength,wav.length);await service.call('resource_cancel',{taskId:task.id});const response=await upload;assert.equal(response.status,400);assert.equal((await response.json()).code,'CANCELLED');assert.equal(service.conversion.snapshot().jobs.length,0);}
 finally{hold.resolve();await blocking;await http.close();await service.close();await rm(root,{recursive:true,force:true});}
});

test('HTTP shutdown is idempotent when callers close concurrently and after shutdown',async()=>{
 const root=await mkdtemp(join(tmpdir(),'http-close-')),service=await MusicService.open(root,()=>{throw Error('unused');},async()=>new Uint8Array(),false,undefined,undefined,undefined,testResources()),http=await serveHttp(service,{read:async()=>new Uint8Array(),has:()=>false,embedded:false});
 try{await Promise.all([http.close(),http.close()]);await http.close();}finally{await service.close();await rm(root,{recursive:true,force:true});}
});
