import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile,writeFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {MusicService} from '../service/service.ts';import {testResources} from '../service/resources/testing.ts';import {serveHttp} from './http.ts';import {Client} from '@modelcontextprotocol/sdk/client/index.js';import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
const read=(p:string)=>readFile(resolve('dist',p));
const driver={installed:()=>true,prepare:async()=>{},cleanReference:async()=>{throw Error('must remain queued');},generate:async()=>{throw Error('must remain queued');}};
test('HTTP and MCP share resource state; queued reference cancellation preserves input and budget survives restart',async()=>{
 const root=await mkdtemp(join(tmpdir(),'resource-api-'));let service=await MusicService.open(root,()=>{throw Error('unused');},read,false,undefined,driver,undefined,testResources());const http=await serveHttp(service,{read,has:()=>true,embedded:false}),client=new Client({name:'resources',version:'1'});
 const invoke=async(name:string,args:any={})=>{const res=await fetch(http.runtime.url+'/api/'+name,{method:'POST',headers:{authorization:`Bearer ${http.runtime.token}`,'content-type':'application/json'},body:JSON.stringify(args)});assert.equal(res.status,200);return res.json();};
 try{assert.equal((await fetch(http.runtime.url+'/api/resource_status',{method:'POST'})).status,401);await client.connect(new StreamableHTTPClientTransport(new URL(http.runtime.url+'/mcp'),{requestInit:{headers:{authorization:`Bearer ${http.runtime.token}`}}}));const tools=(await client.listTools()).tools;assert.equal(tools.find(t=>t.name==='resource_status')?.annotations?.readOnlyHint,true);assert.equal(tools.find(t=>t.name==='resource_cancel')?.annotations?.readOnlyHint,false);await invoke('resource_pause');const voice=service.speech.addVoice('原音',await readFile('public/tts-presets/official.wav'),true);await new Promise(r=>setImmediate(r));const status=await invoke('resource_status');assert.equal(status.paused,true);assert.equal(status.queued[0].engine,'reference');const cancelled=await client.callTool({name:'resource_cancel',arguments:{taskId:voice.id}});assert.equal(cancelled.isError,undefined);assert.equal(service.speech.snapshot().voices[0].processing?.state,'interrupted');assert.ok(service.speech.voiceAudio(voice.id,true).length>44);await invoke('resource_set_limit',{memoryBytes:3*2**30});await invoke('resource_resume');await invoke('resource_release');await client.close();await http.close();await service.close();service=await MusicService.open(root,()=>{throw Error('unused');},read,false,undefined,driver,undefined,testResources());assert.equal((await service.call('resource_status',{})).policy.limits?.memory,3*2**30);assert.ok(service.speech.voiceAudio(voice.id,true).length>44);}
 finally{await client.close().catch(()=>{});await http.close().catch(()=>{});await service.close();await rm(root,{recursive:true,force:true});}
});
test('corrupt resource settings block heavy work while library remains usable and reset repairs settings',async()=>{
 const root=await mkdtemp(join(tmpdir(),'resource-settings-'));await mkdir(join(root,'engines'));await writeFile(join(root,'engines/resources.json'),'broken');const service=await MusicService.open(root,()=>{throw Error('unused');},read,false,undefined,driver,undefined,testResources());try{assert.ok((await service.call('resource_status',{})).configurationError);await service.call('create_project',{projectId:'works',title:'作品'});const sound=await service.speech.createSound('works','语音'),voice=service.speech.addVoice('原音',await readFile('public/tts-presets/official.wav'));const job=service.speech.generate({soundId:sound.id,voiceId:voice.id,text:'你好'});await new Promise(r=>setImmediate(r));assert.equal(service.speech.job(job.id).state,'failed');assert.match(service.speech.job(job.id).error??'',/设置损坏/);const reset=await service.call('resource_set_limit',{memoryBytes:null});assert.equal(reset.configurationError,undefined);assert.equal((await service.call('list_projects',{})).projects.length,1);}finally{await service.close();await rm(root,{recursive:true,force:true});}
});
