import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,writeFile,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {MusicService} from '../service.ts';import {encodeWav} from '../../wav.ts';
const wav=new Uint8Array(encodeWav([new Float32Array(44100).fill(.1)],44100)),unused={unsupported:()=>undefined,installed:()=>false,chooseDirectory:async()=>undefined,prepare:async()=>{},launch:async()=>{throw Error('unused');}};
async function fixture(failConversion=false){const root=await mkdtemp(join(tmpdir(),'studio-conversion-'));const open=()=>MusicService.open(root,()=>{throw Error('unused');},async()=>new Uint8Array(),false,unused,{installed:()=>false,prepare:async()=>{},generate:async()=>{}},{status:()=>({ready:true,message:'ready'}),run:async dir=>{if(failConversion)throw Error('fixture inference failed');for(const n of ['source','converted','vocals'])await writeFile(join(dir,n+'.wav'),wav);return {duration:1};}});return{root,open};}
const wait=async(s:MusicService,id:string)=>{for(let i=0;i<100&&s.conversion.get(id).state!=='succeeded';i++)await new Promise(r=>setTimeout(r,10));assert.equal(s.conversion.get(id).state,'succeeded');};
test('conversion is owned by a project sound with versions, listening decisions, speed and recoverable deletion',async()=>{
 const f=await fixture();let s=await f.open();try{await s.call('create_project',{projectId:'film',title:'项目'});const sound=await s.call('studio_create_sound',{projectId:'film',title:'转换片段',kind:'conversion'}),voice=s.speech.addVoice('目标',wav);
 const job=await s.studio.uploadConversion({soundId:sound.id,name:'original.wav',bytes:wav,voiceId:voice.id,requestId:'first',pitchShiftSemitones:4});await wait(s,job.id);let library=await s.studio.snapshot();assert.equal(library.versions.find(v=>v.id===job.id)?.source.kind,'conversion');assert.equal(job.projectId,'film');assert.equal(job.soundId,sound.id);assert.equal(library.versions.find(v=>v.id===job.id)?.input?.pitchShiftSemitones,4);
 await s.studio.update({versionId:job.id,kept:true,final:true});library=await s.studio.snapshot();assert.equal(library.sounds.find(x=>x.id===sound.id)?.finalVersionId,job.id);assert.equal(library.versions.find(v=>v.id===job.id)?.kept,true);
 const next=await s.call('svc_create_version',{soundId:sound.id,sourceJobId:job.id,voiceId:voice.id,requestId:'second',pitchShiftSemitones:-3});await wait(s,next.id);assert.equal(next.parentId,job.id);assert.equal(next.sourceSha256,job.sourceSha256);assert.equal(next.pitchShiftSemitones,-3);const reset=await s.call('svc_create_version',{soundId:sound.id,sourceJobId:next.id,voiceId:voice.id,requestId:'reset-pitch'});await wait(s,reset.id);assert.equal(reset.pitchShiftSemitones,0);assert.equal(reset.sourceSha256,job.sourceSha256);
 const speed=await s.studio.saveSpeed({versionId:job.id,rate:1.1,requestId:'speed-conversion'});assert.equal(speed.soundId,sound.id);assert.equal(speed.source.kind,'audio');
 await s.studio.update({versionId:job.id,deleted:true});await assert.rejects(s.studio.conversionAudio(job.id,'original'));await s.studio.update({versionId:job.id,deleted:false});assert.deepEqual(await s.studio.conversionAudio(job.id,'original'),wav);
 await s.studio.updateSound({soundId:sound.id,deleted:true});await assert.rejects(s.studio.uploadConversion({soundId:sound.id,name:'x.wav',bytes:wav,voiceId:voice.id,requestId:'bad'}));await assert.rejects(s.studio.conversionAudio(job.id,'converted'));await s.studio.updateSound({soundId:sound.id,deleted:false});
 await s.studio.update({versionId:job.id,deleted:true});await s.studio.purge({kind:'version',id:job.id});assert.equal(s.conversion.get(job.id).purged,true);await s.close();s=await f.open();library=await s.studio.snapshot();assert.ok(!library.versions.some(v=>v.id===job.id));assert.ok(library.versions.some(v=>v.id===next.id));
 }finally{await s.close();await rm(f.root,{recursive:true,force:true});}
});
test('legacy history migrates into a real project by original hash without copying audio and stays idempotent',async()=>{
 const f=await fixture();let s=await f.open();try{const voice=s.speech.addVoice('目标',wav),a=s.conversion.add('legacy.wav',wav,{...voice,audio:wav},'legacy-a');await wait(s,a.id);const b=s.conversion.add('legacy.wav',wav,{...voice,audio:wav},'legacy-b');await wait(s,b.id);await assert.rejects(s.studio.uploadConversion({soundId:'missing-sound',name:'x.wav',bytes:wav,voiceId:voice.id,requestId:'invalid-owner'}));let library=await s.studio.snapshot();const sound=library.sounds.find(x=>x.kind==='conversion')!;assert.equal(library.projects.find(p=>p.id===sound.projectId)?.title,'以前的音色转换');assert.equal(library.versions.filter(v=>v.soundId===sound.id).length,2);assert.equal(s.conversion.get(a.id).soundId,sound.id);assert.deepEqual(await readFile(join(f.root,'conversion',a.id,'original.wav')),Buffer.from(wav));await s.close();s=await f.open();library=await s.studio.snapshot();assert.equal(library.sounds.filter(x=>x.kind==='conversion').length,1);assert.equal(library.versions.filter(v=>v.soundId===sound.id).length,2);
 }finally{await s.close();await rm(f.root,{recursive:true,force:true});}
});
test('active conversion prevents sound/project deletion; cancel and retry keep ownership and preserve failed history',async()=>{
 const f=await fixture(),s=await f.open();try{await s.call('create_project',{projectId:'film',title:'项目'});const sound=await s.call('studio_create_sound',{projectId:'film',title:'转换',kind:'conversion'}),voice=s.speech.addVoice('目标',wav);
 // Hold the native queue behind an existing speech preparation, without launching any model.
 let release!:()=>void;const blocker=new Promise<void>(r=>release=r);const originalPrepare=(s.speech as any).driver.prepare;(s.speech as any).driver.prepare=async()=>blocker;await s.speech.prepare('/unused');
 try{const job=await s.studio.uploadConversion({soundId:sound.id,name:'song.wav',bytes:wav,voiceId:voice.id,requestId:'queued'});await assert.rejects(s.studio.updateSound({soundId:sound.id,deleted:true}),/取消/);await assert.rejects(s.studio.updateProject({projectId:'film',deleted:true}),/取消/);
  await s.studio.cancel(job.id);assert.equal(s.conversion.get(job.id).state,'cancelled');const retry=await s.call('svc_retry',{jobId:job.id});assert.equal(retry.soundId,sound.id);assert.equal(retry.parentId,job.id);await s.studio.cancel(retry.id);
  await s.studio.updateProject({projectId:'film',deleted:true});await assert.rejects(s.studio.conversionAudio(job.id,'original'));await assert.rejects(s.call('svc_retry',{jobId:job.id}));await s.studio.updateProject({projectId:'film',deleted:false});assert.deepEqual(await s.studio.conversionAudio(job.id,'original'),wav);
 }finally{release();(s.speech as any).driver.prepare=originalPrepare;}
 }finally{await s.close();await rm(f.root,{recursive:true,force:true});}
});
test('scoped conversion pagination returns ten latest versions plus selected/final, never all conversion history',async()=>{
 const f=await fixture(),s=await f.open();try{await s.call('create_project',{projectId:'film',title:'项目'});const sound=await s.call('studio_create_sound',{projectId:'film',title:'转换',kind:'conversion'}),voice=s.speech.addVoice('目标',wav),ids:string[]=[];
 for(let i=0;i<12;i++){const job=await s.studio.uploadConversion({soundId:sound.id,name:'song.wav',bytes:wav,voiceId:voice.id,requestId:`page-${i}`});await wait(s,job.id);ids.push(job.id);}
 await s.studio.update({versionId:ids[0],final:true});const page=await s.call('studio_library',{conversionSoundId:sound.id,conversionPage:1,selectedVersionId:ids[1]});assert.equal(page.conversionPagination?.total,12);assert.equal(page.conversionPagination?.versionIds.length,10);assert.equal(page.conversionPagination?.versionIds[0],ids[11]);assert.ok(page.versions.some(v=>v.id===ids[0]));assert.ok(page.versions.some(v=>v.id===ids[1]));
 const last=await s.call('studio_library',{conversionSoundId:sound.id,conversionPage:99});assert.equal(last.conversionPagination?.page,2);assert.equal(last.conversionPagination?.versionIds.length,2);assert.equal(last.versions.filter(v=>v.soundId===sound.id).length,2);const initial=await s.call('studio_library',{paginateConversions:true});assert.equal(initial.versions.filter(v=>v.soundId===sound.id).length,0);await s.studio.update({versionId:ids[5],deleted:true});const visible=await s.call('studio_library',{conversionSoundId:sound.id,conversionPage:1});assert.equal(visible.conversionPagination?.total,11);assert.ok(!visible.conversionPagination?.versionIds.includes(ids[5]));const trash=await s.call('studio_library',{paginateConversions:true,includeDeletedConversions:true});assert.deepEqual(trash.versions.filter(v=>v.soundId===sound.id).map(v=>v.id),[ids[5]]);
 }finally{await s.close();await rm(f.root,{recursive:true,force:true});}
});
test('failed legacy jobs retain original and state; purged project never returns when the same original is uploaded again',async()=>{
 const f=await fixture(true);let s=await f.open();try{const voice=s.speech.addVoice('目标',wav),job=s.conversion.add('failed.wav',wav,{...voice,audio:wav},'failed-old');for(let i=0;i<100&&s.conversion.get(job.id).state!=='failed';i++)await new Promise(r=>setTimeout(r,10));assert.equal(s.conversion.get(job.id).state,'failed');let library=await s.studio.snapshot();const version=library.versions.find(v=>v.id===job.id)!;assert.equal(version.state,'failed');assert.deepEqual(await s.studio.conversionAudio(job.id,'original'),wav);const oldSound=library.sounds.find(x=>x.id===version.soundId)!;
 await s.studio.updateProject({projectId:oldSound.projectId,deleted:true});await s.studio.purge({kind:'project',id:oldSound.projectId});await s.close();s=await f.open();library=await s.studio.snapshot();assert.ok(!library.versions.some(v=>v.id===job.id));assert.ok(!library.sounds.some(x=>x.id===oldSound.id));
 const fresh=await s.studio.uploadConversion({name:'same-original.wav',bytes:wav,voiceId:voice.id,requestId:'fresh-after-purge'});assert.notEqual(fresh.soundId,oldSound.id);assert.notEqual(fresh.projectId,oldSound.projectId);assert.deepEqual(await s.studio.conversionAudio(fresh.id,'original'),wav);
 }finally{await s.close();await rm(f.root,{recursive:true,force:true});}
});
