import {readReferenceWav} from './reference-file.ts';
import './style.css';
import {backend} from '../service.ts';
import {encodeWav} from '../../wav.ts';
import type {SpeechSound,SpeechVersion,SpeechVoice} from '../../service/tts/speech.ts';
import type {Project} from '../../service/projects/store.ts';
import type {OperationResults} from '../../service/operations.ts';
const root=document.querySelector<HTMLDivElement>('#app')!;
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const $=<T extends HTMLElement=HTMLElement>(selector:string)=>document.querySelector<T>(selector)!;
const time=(n=0)=>`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
if(!backend){root.innerHTML=`<section class="no-service"><h1>语音创作需要本地服务</h1><p>请运行 Music Room 本地程序，然后从它的页面打开「语音创作」。</p><code>npm run serve -- --workspace ~/Music/MusicRoom</code><a href="./">返回音乐工作台</a></section>`;}else{void start();}
async function start(){
 const api=backend!;
 let data:OperationResults['tts_library'],projects:Project[]=[],projectId='',soundId='',versionId='',compare:string[]=[],busy='',polling=false,signature='',toastTimer:ReturnType<typeof setTimeout>;
 const urls=new Map<string,string>();let mediaEpoch=0;let directoryDraft:string|undefined;
 type Draft={text:string;emotion:string;voiceId:string;parentId?:string};let drafts:Record<string,Draft>={};
 const draftKey=`music-room-speech-drafts:${api.bootstrap.workspace}`;
 const selectionKey=`music-room-speech-selection:${api.bootstrap.workspace}`;
 try{const saved=JSON.parse(localStorage.getItem(selectionKey)??'{}');if(typeof saved.projectId==='string')projectId=saved.projectId;if(typeof saved.soundId==='string')soundId=saved.soundId;}catch{}
 try{drafts=JSON.parse(localStorage.getItem(draftKey)??'{}');}catch{}
 const saveDrafts=()=>{try{localStorage.setItem(draftKey,JSON.stringify(drafts));}catch{notify('草稿暂时无法保存在浏览器，请复制文字备份。');}};
 const project=()=>projects.find(p=>p.id===projectId);
 const sounds=()=>data.sounds.filter(s=>s.projectId===projectId);
 const sound=()=>data.sounds.find(s=>s.id===soundId);
 const versions=()=>data.versions.filter(v=>v.soundId===soundId&&!v.deleted).slice().reverse();
 const version=()=>data.versions.find(v=>v.id===versionId&&!v.deleted);
 const draft=()=>drafts[soundId]??(drafts[soundId]={text:'',emotion:'',voiceId:data.voices[0]?.id??''});
 root.innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="./speech.html"><span class="brand-mark">♫</span><div><strong>Music Room</strong><small>把想法，变成声音。</small></div></a><button class="primary" data-action="new-project">＋ 新建项目</button><span class="nav-label">我的项目</span><nav id="projects"></nav><a class="music-link" href="./">↗ 音乐工作台</a><p class="local-note">● 文件保存在本机项目目录</p></aside><main id="workspace"><p class="loading" role="status">正在读取语音项目…</p></main></div><div id="toast" class="toast" role="status" aria-live="polite" hidden></div><dialog id="dialog"></dialog>`;
 const dialog=$<HTMLDialogElement>('#dialog');
 function notify(message:string,undo?:()=>Promise<void>){clearTimeout(toastTimer);const t=$('#toast');t.textContent=message;t.hidden=false;if(undo){const b=document.createElement('button');b.textContent='撤销';b.onclick=()=>{void action('undo',undo);};t.append(b);}toastTimer=setTimeout(()=>{t.hidden=true;},9000);}
 function pause(){mediaEpoch++;document.querySelectorAll<HTMLAudioElement>('audio').forEach(a=>a.pause());}
 function render(){
  try{localStorage.setItem(selectionKey,JSON.stringify({projectId,soundId}));}catch{}
  const savedAudio=document.getElementById('version-audio') as HTMLAudioElement|null;
  const active=document.activeElement as HTMLInputElement|HTMLTextAreaElement|null,focus=active?.id,position=active&&'selectionStart'in active?active.selectionStart:null,end=active&&'selectionEnd'in active?active.selectionEnd:null;
  const opened=[...document.querySelectorAll<HTMLDetailsElement>('#workspace details[open]')].map(d=>d.id);
  $('#projects').innerHTML=projects.map(p=>`<button class="project-link ${p.id===projectId?'active':''}" data-action="project" data-id="${p.id}" aria-current="${p.id===projectId?'page':'false'}"><span>▧</span><span>${esc(p.title)}<small>${data.sounds.filter(s=>s.projectId===p.id).length} 个语音</small></span></button>`).join('');
  const s=sound(),vs=versions();if(!version())versionId=s?.finalVersionId??vs[0]?.id??'';
  $('#workspace').innerHTML=`<header class="project-header"><div><div class="eyebrow">我的项目 / 语音创作</div><h1>${esc(project()?.title??'先创建一个项目')}</h1><p>写下要说的话，听一听，再决定哪一版更合适。</p></div><button class="secondary" data-action="deliverables">项目成品 ${sounds().filter(s=>s.finalVersionId).length} ↗</button></header>${engineMarkup()}
  <section class="sounds-section"><div class="section-label"><h2>这个项目的语音 <span>${sounds().length}</span></h2><button class="quiet accent" data-action="new-sound" ${project()?'':'disabled'}>＋ 新语音</button></div><div class="sound-tabs">${sounds().map(s=>`<button class="sound-tab ${s.id===soundId?'selected':''}" data-action="sound" data-id="${s.id}" aria-pressed="${s.id===soundId}"><span class="sound-icon">“</span><span><strong>${esc(s.title)}</strong><small>${data.versions.filter(v=>v.soundId===s.id&&!v.deleted).length} 个版本${s.finalVersionId?' · 已选成品':''}</small></span></button>`).join('')}</div></section>
  ${s?`<div class="creative-grid"><section class="listening-space"><div class="sound-heading"><div><div class="eyebrow">普通语音 / IndexTTS 2.0</div><h2>${esc(s.title)}</h2></div></div>${playerMarkup()}${versionsMarkup()}</section>${composerMarkup()}</div>`:`<section class="empty-project"><span>“</span><h2>先做出一个声音。</h2><p>一句开场白，一段旁白，或一篇朗读。</p><button class="primary" data-action="${project()?'new-sound':'new-project'}">${project()?'＋ 创建第一个语音':'＋ 创建项目'}</button></section>`}
  <footer>所有成功版本均保存为 WAV，关闭页面后任务继续。<button class="quiet" data-action="trash">回收站</button></footer>`;
  for(const id of opened){const details=document.getElementById(id) as HTMLDetailsElement|null;if(details)details.open=true;}
  $<HTMLInputElement>('#engine-directory').oninput=e=>{directoryDraft=(e.target as HTMLInputElement).value;};
  if(s){const d=draft();$<HTMLTextAreaElement>('#speech-text').oninput=e=>{d.text=(e.target as HTMLTextAreaElement).value;saveDrafts();};$<HTMLTextAreaElement>('#speech-emotion').oninput=e=>{d.emotion=(e.target as HTMLTextAreaElement).value;saveDrafts();};$<HTMLSelectElement>('#speech-voice').onchange=e=>{d.voiceId=(e.target as HTMLSelectElement).value;saveDrafts();};$<HTMLFormElement>('#speech-form').onsubmit=e=>{e.preventDefault();void generate();};const v=version();if(v?.state==='succeeded'){const a=$<HTMLAudioElement>('#version-audio');if(savedAudio?.dataset.version===v.id){a.replaceWith(savedAudio);$('#audio-loading').hidden=!!savedAudio.src;}else loadAudio(a,v.id,'audio');}}
  if(focus){const input=document.getElementById(focus);input?.focus({preventScroll:true});if((input instanceof HTMLTextAreaElement||input instanceof HTMLInputElement)&&position!==null&&input.type!=='file')try{input.setSelectionRange(position,end??position);}catch{}}
 }
 function engineMarkup(){const status=data.status;return `<details id="engine-settings" class="engine-settings" ${status.phase!=='ready'?'open':''}><summary><span class="engine-dot ${status.canGenerate?'ready':''}"></span>IndexTTS 2.0 <span>${status.canGenerate?'已就绪':status.phase==='preparing'?'准备中':status.phase==='failed'?'准备失败':'尚未准备'}</span><span class="settings-label">环境与模型</span></summary><div class="engine-body"><p id="engine-message" role="status">${esc(status.message)}</p>${status.phase==='preparing'?'<button class="secondary" data-action="cancel-prepare">取消准备</button>':`<button class="primary" data-action="prepare" ${busy==='prepare'?'disabled':''}>${status.canGenerate?'检查 / 修复环境':'准备语音模型'}</button>`}<details id="installation-details"><summary>安装位置与日志</summary><label for="engine-directory">专用安装目录</label><input id="engine-directory" value="${esc(directoryDraft??status.directory)}" placeholder="专用空目录的绝对路径"><p class="field-note">Python、依赖和模型保存在这个目录。首次准备需要联网，文件约 8–10 GB；再次使用会复用下载。</p><pre>${esc(status.logs.join('\n'))}</pre></details></div></details>`;}
 function playerMarkup(){const v=version();if(!v)return `<div class="player-empty"><span>“</span><h3>第一版，从要说的话开始。</h3><p>选择参考声音，填写正文，然后生成。</p></div>`;const done=v.state==='succeeded';return `<div class="player-card"><div class="player-top"><strong>V${v.number} <span class="badge">${stateName(v)}</span></strong><button class="quiet" data-action="details" data-id="${v.id}">版本详情 ↗</button></div>${done?`<div class="audio-space"><audio id="version-audio" data-version="${v.id}" controls preload="metadata" aria-label="试听 V${v.number}"></audio><span id="audio-loading" class="field-note">正在读取已保存音频…</span></div>`:`<div class="pending-audio"><span>${v.state==='running'?'◌':'“'}</span><p role="status">${esc(v.stage)}</p>${v.error?'<p>创作要求已保留，可以重试。</p>':''}</div>`}<p class="version-caption">参考声音：${esc(v.voiceName)}</p>${done?`<div class="version-actions"><button class="secondary" data-action="keep" data-id="${v.id}">${v.kept?'★ 已留作灵感':'☆ 保留灵感'}</button><button class="secondary" data-action="final" data-id="${v.id}">${sound()?.finalVersionId===v.id?'✓ 已选作成品':'选作成品'}</button><button class="quiet accent" data-action="iterate" data-id="${v.id}">修改这版</button><button class="quiet" data-action="download" data-id="${v.id}">↓ 下载 WAV</button></div>`:''}</div>`;}
 function stateName(v:SpeechVersion){return {queued:'排队中',running:'正在生成',succeeded:'可试听',failed:'生成失败',cancelled:'已取消',interrupted:'已中断'}[v.state];}
 function versionsMarkup(){const vs=versions();return `<div class="versions-heading"><h3>版本 <span>${vs.length}</span></h3><button class="quiet accent" data-action="compare" ${compare.length===2?'':'disabled'}>比较${compare.length?`（${compare.length}/2）`:''} ↗</button></div><p class="field-note">勾选两版分别试听；每次生成都保留已有结果。</p><div class="version-list">${vs.map(v=>`<article class="version-row ${v.id===versionId?'selected':''}"><input type="checkbox" aria-label="比较 V${v.number}" data-compare="${v.id}" ${compare.includes(v.id)?'checked':''} ${v.state!=='succeeded'?'disabled':''}><button class="version-select" data-action="version" data-id="${v.id}" aria-pressed="${v.id===versionId}"><span><strong>V${v.number}</strong>${v.kept?'<span class="star">★</span>':''}${sound()?.finalVersionId===v.id?'<span class="badge">成品</span>':''}<small>${stateName(v)}${v.artifact?' · '+time(v.artifact.duration):''}</small></span><p>${esc(v.text)}</p>${v.parentId?`<small>基于 V${data.versions.find(p=>p.id===v.parentId)?.number??'?'}${data.versions.find(p=>p.id===v.parentId)?.deleted?'（已删除）':''}</small>`:''}</button>${['queued','running'].includes(v.state)?`<button class="quiet" data-action="cancel" data-id="${v.id}">取消</button>`:`<details class="row-menu"><summary aria-label="V${v.number} 更多操作">···</summary><div><button data-action="iterate" data-id="${v.id}">${v.state==='succeeded'?'基于这版修改':'恢复要求并重试'}</button><button class="danger" data-action="delete" data-id="${v.id}">删除版本</button></div></details>`}</article>`).join('')||'<p class="empty-versions">生成的版本会出现在这里。</p>'}</div>`;}
 function composerMarkup(){const d=draft(),voice=data.voices.find(v=>v.id===d.voiceId);return `<aside class="composer-panel"><h2>✳ ${versions().length?'再试一个版本':'做出第一个版本'}</h2><p>音色、文字、情绪，各自说清楚。</p><form id="speech-form"><div class="label-row"><label for="speech-voice">参考声音</label><button type="button" class="quiet accent" data-action="upload-voice">＋ 添加声音</button></div><select id="speech-voice" required><option value="">选择参考声音</option>${data.voices.map(v=>`<option value="${v.id}" ${v.id===d.voiceId?'selected':''}>${esc(v.name)}</option>`).join('')}</select>${voice?`<button type="button" class="quiet" data-action="listen-voice" data-id="${voice.id}">▶ 试听参考声音 · ${time(voice.duration)}</button>`:'<p class="field-note">参考音频决定音色。准备模型后提供一个官方示例，也可以添加自己的声音。</p>'}
  <label for="speech-text">要说的文字</label><textarea id="speech-text" required maxlength="8000" rows="7" placeholder="输入旁白或朗读正文。">${esc(d.text)}</textarea><label for="speech-emotion">情绪描述（可选）</label><textarea id="speech-emotion" maxlength="2000" rows="2" placeholder="例如：平静、温暖。留空时沿用参考声音的情绪。">${esc(d.emotion)}</textarea>${d.parentId?`<div class="based-on">基于 V${data.versions.find(v=>v.id===d.parentId)?.number} 修改<button type="button" class="quiet" data-action="clear-parent">取消</button></div>`:''}<button type="submit" class="primary generate" ${!data.status.canGenerate||busy==='generate'?'disabled':''}>✳ ${busy==='generate'?'正在提交…':'生成新版本'}</button><p class="field-note">${data.status.canGenerate?'IndexTTS 2.0 · 在本机生成。新版本不会覆盖旧版。':'先准备语音环境，再生成。'}</p></form></aside>`;}
 async function refresh(force=false){if(polling)return;polling=true;try{const [library,p]=await Promise.all([api.call('tts_library',{}),api.call('list_projects',{})]);const next=JSON.stringify([library,p]);data=library;projects=p.projects;if(!projects.some(p=>p.id===projectId))projectId=data.sounds.find(s=>projects.some(p=>p.id===s.projectId))?.projectId??projects[0]?.id??'';if(!sounds().some(s=>s.id===soundId)){soundId=sounds()[0]?.id??'';versionId='';compare=[];}if(soundId&&!draft().voiceId&&data.voices.length)draft().voiceId=data.voices[0].id;if(force||next!==signature){signature=next;render();}}catch(error){notify(error instanceof Error?error.message:String(error));if(!data)$('#workspace').innerHTML='<p class="loading">连接失败，请检查本地服务后刷新。</p>';}finally{polling=false;}}
 async function action(name:string,fn:()=>Promise<void>){if(busy)return;busy=name;try{await fn();}catch(error){notify(error instanceof Error?error.message:String(error));}finally{busy='';if(data)render();}}
 async function generate(){const s=sound();if(!s)return;const d=structuredClone(draft());if(!d.text.trim()||!d.voiceId)return;await action('generate',async()=>{const v=await api.call('tts_generate',{soundId:s.id,voiceId:d.voiceId,text:d.text,emotion:d.emotion,parentId:d.parentId});if(soundId===s.id){versionId=v.id;compare=[];}await refresh(true);notify(`${s.title} · V${v.number} 已提交，关闭页面后仍会继续生成。`);});}
 async function audioUrl(id:string,kind:'audio'|'voice'){const key=kind+id;if(urls.has(key))return urls.get(key)!;const response=await fetch(`/speech/${kind==='voice'?'voice-audio':'audio'}/${id}`,{headers:{authorization:`Bearer ${api.bootstrap.token}`}});if(!response.ok){const error=await response.json();throw new Error(error.message??'音频无法读取');}const url=URL.createObjectURL(await response.blob());urls.set(key,url);return url;}
 function loadAudio(audio:HTMLAudioElement,id:string,kind:'audio'|'voice'){if(!audio)return;const epoch=mediaEpoch;void audioUrl(id,kind).then(url=>{if(!audio.isConnected||epoch!==mediaEpoch)return;audio.src=url;const note=document.getElementById('audio-loading');if(note)note.hidden=true;}).catch(e=>notify(e.message));}
 function showDialog(title:string,content:string){pause();dialog.innerHTML=`<div class="dialog-header"><h2>${title}</h2><button class="quiet close" data-action="close" aria-label="关闭">×</button></div>${content}`;if(!dialog.open)dialog.showModal();}
 function newProject(){showDialog('新建项目','<form id="project-form"><p>把这次创作需要的声音放在一起。</p><label for="project-name">项目名称</label><input id="project-name" required maxlength="120" placeholder="例如：秋日短片"><button class="primary" type="submit">创建项目 →</button></form>');$<HTMLFormElement>('#project-form').onsubmit=e=>{e.preventDefault();void action('project',async()=>{const p=await api.call('create_project',{projectId:`work-${crypto.randomUUID()}`,title:$<HTMLInputElement>('#project-name').value.trim()});projectId=p.id;soundId='';versionId='';dialog.close();await refresh(true);newSound();});};}
 function newSound(){showDialog('添加一个语音','<form id="sound-form"><label for="sound-title">声音名称</label><input id="sound-title" required maxlength="120" placeholder="例如：片头旁白"><button type="submit" class="primary">开始创作 →</button></form>');$<HTMLFormElement>('#sound-form').onsubmit=e=>{e.preventDefault();const pid=projectId;void action('sound',async()=>{const s=await api.call('tts_create_sound',{projectId:pid,title:$<HTMLInputElement>('#sound-title').value.trim()});if(projectId===pid){soundId=s.id;versionId='';}dialog.close();await refresh(true);$<HTMLTextAreaElement>('#speech-text')?.focus();});};}
 function uploadVoice(){showDialog('添加参考声音',`<form id="voice-form"><label for="voice-name">声音名称</label><input id="voice-name" required maxlength="120" placeholder="例如：我的旁白声音"><label for="voice-file">参考音频</label><input id="voice-file" type="file" accept=".wav,audio/wav" required><p class="field-note">选择 10 分钟以内、清晰的 PCM WAV 人声；压缩音频或视频请先导出 WAV 片段。超过 15 秒时使用前 15 秒；保存后可以跨项目复用。</p><button type="submit" class="primary">保存参考声音</button><p id="voice-progress" role="status"></p></form>`);$<HTMLFormElement>('#voice-form').onsubmit=e=>{e.preventDefault();const file=$<HTMLInputElement>('#voice-file').files?.[0],name=$<HTMLInputElement>('#voice-name').value.trim(),sid=soundId;if(!file)return;void action('voice',async()=>{if(file.size>50*1024*1024)throw new Error('请选择小于 50 MiB 的参考音频');$('#voice-progress').textContent='正在读取并保存声音…';const context=new AudioContext({sampleRate:44100});let decoded:AudioBuffer;try{decoded=await context.decodeAudioData(await readReferenceWav(file));}finally{await context.close();}const duration=Math.min(15,decoded.duration);if(duration<.3)throw new Error('参考声音至少需要 0.3 秒');const offline=new OfflineAudioContext(1,Math.ceil(duration*22050),22050),source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();const pcm=await offline.startRendering(),bytes=encodeWav([pcm.getChannelData(0)],22050);const response=await fetch(`/speech/voices?name=${encodeURIComponent(name)}`,{method:'POST',headers:{authorization:`Bearer ${api.bootstrap.token}`,'content-type':'audio/wav'},body:bytes});const value=await response.json() as SpeechVoice&{message?:string};if(!response.ok)throw new Error(value.message??'参考声音保存失败');if(sid)drafts[sid]={...drafts[sid],voiceId:value.id};saveDrafts();dialog.close();await refresh(true);notify(duration<decoded.duration?'已保存参考声音，使用原文件的前 15 秒。':'参考声音已保存，可重复使用。');});};}
 async function compareVersions(){const vs=compare.map(id=>data.versions.find(v=>v.id===id)!);showDialog('听听，哪一版更合适',`<p>每版独立试听，一次只播放一个。</p><div class="compare-grid">${vs.map((v,i)=>`<article><span class="compare-letter">${i?'B':'A'}</span><h3>V${v.number}</h3><p>${esc(v.text)}</p><audio controls preload="metadata" id="compare-audio-${i}" aria-label="试听 ${i?'B':'A'} 版"></audio><button class="secondary" data-action="choose-compared" data-id="${v.id}">选这版作成品</button></article>`).join('')}</div><p class="field-note">比较原始音频，未做响度归一化。</p>`);vs.forEach((v,i)=>loadAudio($<HTMLAudioElement>(`#compare-audio-${i}`),v.id,'audio'));}
 async function update(id:string,patch:{kept?:boolean;final?:boolean;deleted?:boolean}){await api.call('tts_update_version',{versionId:id,...patch});await refresh(true);}
 function dispatch(actionName:string,id?:string){const v=data?.versions.find(v=>v.id===(id??versionId));switch(actionName){
  case 'new-project':newProject();break;case 'new-sound':newSound();break;case 'upload-voice':uploadVoice();break;
  case 'project':pause();projectId=id!;soundId=sounds()[0]?.id??'';versionId='';compare=[];render();break;
  case 'sound':pause();soundId=id!;versionId='';compare=[];render();break;
  case 'version':pause();versionId=id!;render();break;
  case 'close':pause();dialog.close();render();break;
  case 'prepare':{const directory=$<HTMLInputElement>('#engine-directory')?.value.trim()||data.status.directory;void action('prepare',async()=>{await api.call('tts_prepare',{directory});await refresh(true);});break;}
  case 'cancel-prepare':void action('prepare',async()=>{await api.call('tts_cancel_preparation',{});await refresh(true);});break;
  case 'cancel':if(v)void action('cancel',async()=>{await api.call('tts_cancel',{versionId:v.id});await refresh(true);});break;
  case 'keep':if(v)void action('keep',()=>update(v.id,{kept:!v.kept}));break;
  case 'final':if(v)void action('final',()=>update(v.id,{final:sound()?.finalVersionId!==v.id}));break;
  case 'delete':if(v)void action('delete',async()=>{pause();compare=compare.filter(id=>id!==v.id);if(draft().parentId===v.id)draft().parentId=undefined;await update(v.id,{deleted:true});notify(`V${v.number} 已移入回收站。`,()=>update(v.id,{deleted:false}));});break;
  case 'restore':if(v)void action('restore',async()=>{await update(v.id,{deleted:false});dialog.close();notify('版本已恢复。');});break;
  case 'iterate':if(v){drafts[soundId]={text:v.text,emotion:v.emotion??'',voiceId:v.voiceId,parentId:v.state==='succeeded'&&!v.deleted?v.id:undefined};saveDrafts();render();$('#speech-text').focus();notify('已恢复这版的正文、参考声音和情绪要求。');}break;
  case 'clear-parent':draft().parentId=undefined;saveDrafts();render();break;
  case 'download':if(v)void action('download',async()=>{const url=await audioUrl(v.id,'audio'),a=document.createElement('a');a.href=url;a.download=`${data.sounds.find(s=>s.id===v.soundId)?.title??'语音'}-V${v.number}.wav`;a.click();});break;
  case 'listen-voice':{const voice=data.voices.find(v=>v.id===id);if(voice){showDialog('试听参考声音',`<p>${esc(voice.name)}</p><audio id="voice-preview" controls preload="metadata"></audio>`);loadAudio($<HTMLAudioElement>('#voice-preview'),voice.id,'voice');}break;}
  case 'compare':if(compare.length===2)void compareVersions();break;
  case 'choose-compared':if(v)void action('final',async()=>{await update(v.id,{final:true});pause();versionId=v.id;dialog.close();notify('已选作成品，其他版本保留。');});break;
  case 'details':if(v)showDialog(`V${v.number} · 版本详情`,`<dl><dt>引擎</dt><dd>IndexTTS 2.0</dd><dt>参考声音</dt><dd>${esc(v.voiceName)}</dd><dt>正文</dt><dd>${esc(v.text)}</dd><dt>情绪</dt><dd>${esc(v.emotion||'沿用参考声音')}</dd><dt>状态</dt><dd>${stateName(v)}</dd>${v.error?`<dt>失败原因</dt><dd class="error-detail">${esc(v.error)}</dd>`:''}${v.artifact?`<dt>音频</dt><dd>${time(v.artifact.duration)} · ${v.artifact.sampleRate} Hz · WAV</dd>`:''}</dl>`);break;
  case 'trash':showDialog('回收站',`<p>删除不影响基于它创建的后续版本。</p>${data.versions.filter(v=>v.deleted&&v.projectId===projectId).map(v=>`<div class="trash-row"><span>${esc(data.sounds.find(s=>s.id===v.soundId)?.title)} · V${v.number}</span><button class="quiet accent" data-action="restore" data-id="${v.id}">恢复</button></div>`).join('')||'<p>还没有删除的版本。</p>'}`);break;
  case 'deliverables':showDialog('项目成品',`${sounds().filter(s=>s.finalVersionId).map(s=>{const v=data.versions.find(v=>v.id===s.finalVersionId)!;return `<div class="deliverable"><div><h3>${esc(s.title)}</h3><p>V${v.number} · ${time(v.artifact?.duration)}</p></div><button class="secondary" data-action="download" data-id="${v.id}">下载 WAV</button></div>`;}).join('')||'<p>试听满意后，点击「选作成品」。</p>'}`);break;
 }}
 document.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(button&&!(button instanceof HTMLButtonElement&&button.disabled))dispatch(button.dataset.action!,button.dataset.id);});
 document.addEventListener('change',e=>{const input=e.target as HTMLInputElement;if(!input.matches('[data-compare]'))return;const id=input.dataset.compare!;if(input.checked){if(compare.length===2){input.checked=false;notify('一次比较两版，请先取消一版。');return;}compare.push(id);}else compare=compare.filter(v=>v!==id);render();});
 document.addEventListener('play',e=>{const current=e.target;document.querySelectorAll<HTMLAudioElement>('audio').forEach(a=>{if(a!==current)a.pause();});},true);
 dialog.addEventListener('close',()=>{pause();if(data)render();});
 window.addEventListener('pagehide',()=>{pause();for(const url of urls.values())URL.revokeObjectURL(url);urls.clear();});
 await refresh(true);setInterval(()=>{void refresh();},1800);
}
