import './style.css';
import {updateThemeControls} from './theme.ts';
import {renderWorkspace} from './player.ts';
import {speedControls,bindSpeedControls} from './speed.ts';
import {backend} from '../service.ts';
import type {OperationResults} from '../../service/operations.ts';
import type {StudioInput,StudioVersion} from '../../service/studio/studio.ts';
import {emotionStrengths,emotionStrengthLabels,displayedEmotionStrength,type EmotionStrength} from '../../service/tts/emotion.ts';
import {newCreationDraft,versionCreationDraft} from './creation.ts';
import {encodeWav} from '../../wav.ts';
const root=document.querySelector<HTMLDivElement>('#app')!;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const kindName={clip:'音乐片段',music:'完整音乐',speech:'语音',conversion:'音色转换'};
const pitchLabel=(n=0)=>n===0?'不升降调':`${n>0?'升':'降'} ${Math.abs(n)} 半音`;
const time=(n=0)=>`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
if(!backend)root.innerHTML='<main class="standalone"><h1>Music Room</h1><p>请从本地服务打开创作空间。</p><code>npm run serve -- --workspace ~/Music/MusicRoom</code><p><a href="./score.html">打开 MIDI 编辑器</a></p></main>';else void start();
async function start(){
 const api=backend!;let data:OperationResults['studio_library'],projectId='',soundId='',versionId='',signature='',busy=false,mediaEpoch=0,autoplayId='',selectedVersions=new Set<string>();
 let workspaceView:'project'|'voices'='project',libraryVoiceId='',conversionPage=1;
 const conversionRequests=new Map<string,{key:string;id:string}>();
 const cache=new Map<string,string>(),drafts:Record<string,StudioInput>={};const key=`music-room-studio:${api.bootstrap.workspace}`;
 try{const saved=JSON.parse(localStorage.getItem(key)??'{}');projectId=saved.projectId??'';soundId=saved.soundId??'';versionId=saved.versionId??'';Object.assign(drafts,saved.drafts??{});workspaceView=saved.workspaceView==='voices'?'voices':'project';libraryVoiceId=saved.libraryVoiceId??'';}catch{}
 const save=()=>{try{localStorage.setItem(key,JSON.stringify({projectId,soundId,versionId,drafts,workspaceView,libraryVoiceId}));}catch{}};
 const projects=()=>data.projects.filter(p=>!p.deleted);
 const project=()=>projects().find(p=>p.id===projectId),sounds=()=>data.sounds.filter(s=>s.projectId===projectId&&!s.deleted),sound=()=>sounds().find(s=>s.id===soundId),versions=()=>{if(sound()?.kind==='conversion'){const ids=data.conversionPagination?.soundId===soundId?data.conversionPagination.versionIds:[];return ids.map(id=>data.versions.find(v=>v.id===id)).filter((v):v is StudioVersion=>!!v&&!v.deleted);}return data.versions.filter(v=>v.soundId===soundId&&!v.deleted).toReversed();},version=()=>data.versions.find(v=>v.id===versionId&&v.soundId===soundId&&!v.deleted);
 const selectable=(v:StudioVersion)=>!['queued','running'].includes(v.state)&&!v.renderJobId;
 const voiceList=()=>data.voices.filter(v=>!v.deleted).toSorted((a,b)=>Number(!!b.builtinId)-Number(!!a.builtinId)||Number(!!b.favorite)-Number(!!a.favorite));
 const draft=()=>drafts[soundId]??(drafts[soundId]=newCreationDraft(soundId,voiceList()[0]?.id));
 root.innerHTML=`<div class="studio-shell"><aside class="sidebar"><a class="brand" href="./"><span class="brand-symbol">♫</span>Music Room</a><button class="new-project" data-action="new-project">＋ 新建项目</button><div class="nav-caption">项目</div><nav id="projects" aria-label="项目"></nav><button class="library-entry" data-action="voice-library" aria-current="false"><span aria-hidden="true">≋</span> 音色库</button><div class="sidebar-bottom"><div class="theme-switch" role="group" aria-label="界面主题"><button data-theme-choice="light" aria-pressed="false"><i aria-hidden="true">☀</i> 日间</button><button data-theme-choice="dark" aria-pressed="false"><i aria-hidden="true">☾</i> 夜间</button></div><button data-action="trash">回收站</button><button data-action="settings">设置</button><span>保存在本机</span></div></aside><main id="workspace"><p class="loading">正在打开创作空间…</p></main></div><dialog id="dialog" aria-labelledby="dialog-title"></dialog><div id="toast" role="status" aria-live="polite" hidden></div><input id="score-file" type="file" accept=".json,.mid,.midi" hidden>`;
 updateThemeControls();
 const dialog=$<HTMLDialogElement>('#dialog');let toastTimer:ReturnType<typeof setTimeout>;
 function notify(text:string,undo?:()=>Promise<unknown>){clearTimeout(toastTimer);const t=$('#toast');t.textContent=text;t.hidden=false;if(undo){const b=document.createElement('button');b.textContent='撤销';b.onclick=()=>void act(undo);t.append(b);}toastTimer=setTimeout(()=>t.hidden=true,9000);}
 function pause(){mediaEpoch++;document.querySelectorAll<HTMLAudioElement>('audio').forEach(a=>a.pause());}
 function close(){dialog.querySelectorAll('audio').forEach(a=>a.pause());dialog.close();}
 dialog.addEventListener('cancel',()=>{dialog.querySelectorAll('audio').forEach(a=>a.pause());});
 function modal(title:string,html:string,wide=false){dialog.querySelectorAll('audio').forEach(a=>a.pause());dialog.classList.toggle('wide',wide);dialog.innerHTML=`<div class="dialog-frame"><header class="dialog-heading"><h2 id="dialog-title">${esc(title)}</h2><button class="icon-button" data-action="close" aria-label="关闭">×</button></header><div class="dialog-body">${html}</div></div>`;const bar=dialog.querySelector<HTMLElement>('.compose-bottom');if(bar){bar.classList.add('dialog-footer');bar.querySelector('button[type=submit]')?.setAttribute('form','compose-form');dialog.querySelector('.dialog-frame')!.append(bar);}if(!dialog.open)dialog.showModal();}
 async function act(fn:()=>Promise<unknown>){if(busy)return;busy=true;document.body.classList.add('busy');try{await fn();}catch(e){notify((e as Error).message);}finally{busy=false;document.body.classList.remove('busy');}}
 function badge(v:StudioVersion){return v.state==='succeeded'?(sound()?.finalVersionId===v.id?'<span class="tag final">成品</span>':v.kept?'<span class="tag">灵感</span>':''):`<span class="tag ${v.state==='failed'?'error':''}">${esc({queued:'排队中',running:'生成中',failed:'失败',cancelled:'已取消',interrupted:'已中断'}[v.state])}</span>`;}
 function render(){
  const openEntities=[...document.querySelectorAll<HTMLDetailsElement>('.entity-menu[open]')].map(m=>[m.dataset.entityKind,m.dataset.id]);const restoreMenus=()=>{for(const [kind,id] of openEntities)document.querySelector<HTMLDetailsElement>(`.entity-menu[data-entity-kind="${kind}"][data-id="${id}"]`)?.setAttribute('open','');};
  const existing=$<HTMLAudioElement>('#version-audio'),openMenu=$<HTMLDetailsElement>('.more-menu')?.open,previousVersion=existing?.dataset.version;
  if(!project())projectId=projects()[0]?.id??'';
  if(!sound())soundId=sounds()[0]?.id??'';
  if(!version()&&!(sound()?.kind==='conversion'&&data.conversionPagination?.soundId!==soundId))versionId=sound()?.finalVersionId??versions()[0]?.id??'';
  $('[data-action="voice-library"]').setAttribute('aria-current',workspaceView==='voices'?'page':'false');
  const s=sound(),v=version(),vs=versions();selectedVersions=new Set([...selectedVersions].filter(id=>vs.some(v=>v.id===id&&selectable(v))));save();
  $('#projects').innerHTML=projects().map(p=>`<button class="project-link ${p.id===projectId&&workspaceView==='project'?'active':''}" data-action="project" data-id="${p.id}" aria-current="${p.id===projectId&&workspaceView==='project'?'page':'false'}"><span class="project-dot"></span><span>${esc(p.title)}</span><small>${data.sounds.filter(s=>s.projectId===p.id&&!s.deleted).length}</small></button>`).join('');
  if(workspaceView==='voices'){existing?.pause();renderVoiceLibrary();restoreMenus();return;}
  renderWorkspace($('#workspace'),`<header class="project-header ${project()?'workspace-toolbar':''}"><h1>${esc(project()?.title??'每个想法，都可以从这里开始。')}</h1>
  ${project()?`<nav class="sound-nav" aria-label="项目中的声音">${sounds().map(x=>`<button class="sound-tab ${x.id===soundId?'selected':''}" data-action="sound" data-id="${x.id}" data-kind="${x.kind}" aria-pressed="${x.id===soundId}" title="${esc(x.title)} · ${kindName[x.kind]}"><span>${x.kind==='speech'?'◌':'♫'}</span><span>${esc(x.title)}</span></button>`).join('')}</nav><div class="project-actions"><button class="add-sound" data-action="new-sound">＋ 新声音</button>${s?`<button class="primary" data-action="compose">＋ ${vs.length?'再创作一版':'开始创作'}</button>${entityMenu('sound',s.id,'片段')}`:''}<button class="quiet" data-action="deliverables">查看成品 <span>${sounds().filter(s=>s.finalVersionId).length}</span> ↗</button>${entityMenu('project',projectId,'项目')}</div>`:''}</header>
  ${s?`<section class="sound-workspace">
   ${v?`<section class="listening" aria-label="当前版本"><div class="listening-top"><span class="version-label">V${v.number}</span>${badge(v)}${v.speed?`<span class="tag">${v.speed.rate} 倍调速版</span>`:''}<span class="source-label">${v.source.kind==='conversion'?'音色转换':v.source.kind==='speech'?'语音':v.source.kind==='score'?'乐谱合成':'音乐'}${v.duration?' · '+time(v.duration):''}</span></div>
    <div class="player-space">${v.audioPath?`<div id="audio-placeholder">正在读取声音…</div><audio id="version-audio" data-version="${v.id}" data-audio-path="${esc(v.audioPath)}" controls preload="metadata" aria-label="V${v.number} 试听"></audio>${v.source.kind==='conversion'?'':speedControls()}`:v.source.kind==='score'?`<div class="empty-player"><span>♫</span><div><strong>${v.renderJobId?'正在准备试听…':'乐谱已经保存'}</strong><p>${v.renderJobId?esc(v.stage):'合成为音频后，即可在这里试听和下载。'}</p></div><button class="secondary" data-action="render" ${v.renderJobId?'disabled':''}>${v.renderJobId?'准备中':'生成试听音频'}</button></div>`:`<div class="empty-player"><span>${['running','queued'].includes(v.state)?'◷':'◌'}</span><div><strong>${esc(v.stage)}</strong><p>${esc(v.error??(['running','queued'].includes(v.state)?'可以继续做别的声音，完成后会保存在这里。':'创作要求已保留，可以修改后再试。'))}</p></div>${['queued','running'].includes(v.state)?'<button class="quiet" data-action="cancel">取消生成</button>':'<button class="secondary" data-action="iterate">修改后重试</button>'}</div>`}</div>
    <div class="listening-actions">${v.state==='succeeded'?`<button class="${s.finalVersionId===v.id?'chosen':'quiet'}" data-action="final">${s.finalVersionId===v.id?'✓ 已选为成品':'选为成品'}</button><button class="quiet ${v.kept?'chosen':''}" data-action="keep">${v.kept?'★ 已保留灵感':'☆ 保留灵感'}</button><div class="action-spacer"></div>${v.audioPath?'<button class="quiet" data-action="download">↓ 下载</button>':''}<button class="quiet" data-action="iterate">修改这版</button>`:''}<details class="more-menu"><summary aria-label="版本更多操作">•••</summary><div><button data-action="requirements">查看创作要求</button>${v.source.kind==='conversion'?'<button data-action="conversion-original-listen">试听原音</button><button data-action="conversion-original-download">下载原音</button><button data-action="conversion-vocals-listen">试听转换人声</button><button data-action="conversion-vocals-download">下载转换人声</button>':''}${v.source.kind==='score'?`<a href="./score.html#${v.source.id}">查看 MIDI / 音轨 ↗</a><button data-action="midi">下载 MIDI</button>`:''}${selectable(v)?'<button class="danger" data-action="delete">删除版本</button>':''}</div></details></div>
   </section>`:`<div class="empty-sound"><span>${s.kind==='speech'?'“':'♫'}</span><h3>还没有版本，先试一个想法。</h3><p>${s.kind==='conversion'?'上传原始音频，选择目标音色，保留原来的伴奏和背景音。':s.kind==='speech'?'写下要说的话，选择一个参考声音。':'描述你想要的旋律、氛围或用途。'}</p><button class="primary" data-action="compose">开始创作</button></div>`}
   ${vs.length?`<section class="versions ${s.kind==='conversion'?'conversion-versions':''}"><div class="section-heading"><h3>版本 <span>${s.kind==='conversion'?data.conversionPagination?.total??vs.length:vs.length}</span></h3><div>${selectedVersions.size===2&&vs.filter(x=>selectedVersions.has(x.id)).every(x=>x.audioPath)?'<button class="quiet" data-action="compare">试听比较 →</button>':'<span class="muted">勾选可删除，两版音频可比较</span>'}</div></div><div class="version-selection" aria-label="版本批量操作"><button class="quiet" data-action="select-all" ${vs.some(selectable)?'':'disabled'}>全选</button>${selectedVersions.size?`<span class="muted" role="status">已选 ${selectedVersions.size} 版</span><button class="quiet" data-action="clear-selection">取消选择</button><button class="secondary danger" data-action="delete-selected">删除所选（${selectedVersions.size}）</button>`:''}</div><div class="version-list">${vs.map(x=>`<div class="version-row ${x.id===versionId?'selected':''}"><input type="checkbox" aria-label="选择 V${x.number}" data-select-version="${x.id}" ${selectedVersions.has(x.id)?'checked':''} ${selectable(x)?'':'disabled title="请先取消或等待生成完成，再选择版本"'}><button data-action="version" data-id="${x.id}" aria-pressed="${x.id===versionId}"><strong>V${x.number}</strong><span class="version-copy">${x.voiceName?`<span class="version-metadata"><span class="version-voice">${esc(x.voiceName)}</span>${x.input?.emotion?`<span class="version-emotion">情绪：${esc(x.input.emotion)}</span>`:''}${x.source.kind==='speech'?`<span class="version-emotion version-strength">${emotionStrengthLabels[displayedEmotionStrength(x.input??{})]}</span>`:''}</span>`:''}<span class="version-description">${x.speed?`${x.speed.rate} 倍调速 · `:''}${x.source.kind==='conversion'&&x.input?.pitchShiftSemitones?`${pitchLabel(x.input.pitchShiftSemitones)} · `:''}${esc(x.input?.text||(x.source.kind==='conversion'?'音色转换':'已保存的音乐'))}</span></span>${badge(x)}<time>${x.duration?time(x.duration):x.state==='succeeded'?'已完成':esc(x.stage)}</time></button></div>`).join('')}</div>${s.kind==='conversion'?conversionPagination():''}</section>`:''}
   <div class="workspace-footer" ${s.kind==='conversion'?'hidden':''}><button class="quiet" data-action="tools">导入与 Agent 创作</button></div></section>`:`<section class="empty-sound"><span>♫</span><h2>${project()?'这个项目，先从一个声音开始。':'先为你的想法建一个项目。'}</h2><p>一段旋律、一首完整作品，或一句旁白。</p><button class="primary" data-action="${project()?'new-sound':'new-project'}">＋ ${project()?'创建第一个声音':'新建项目'}</button></section>`}`);
  restoreMenus();
  if(openMenu&&previousVersion===v?.id&&$('.more-menu'))$<HTMLDetailsElement>('.more-menu').open=true;
  if(v?.audioPath){const audio=$<HTMLAudioElement>('#version-audio');if(audio===existing){$('#audio-placeholder').hidden=!!existing.src;}else{existing?.pause();void loadAudio(audio,v);} }else existing?.pause();
  if(v?.audioPath&&v.source.kind!=='conversion')bindSpeedControls($<HTMLAudioElement>('#version-audio'),(rate,requestId)=>saveSpeed(v.id,rate,requestId));
  if(autoplayId&&v?.id===autoplayId&&v.audioPath){autoplayId='';void loadAudio($<HTMLAudioElement>('#version-audio'),v,true);}
  document.querySelectorAll<HTMLInputElement>('[data-select-version]').forEach(c=>c.onchange=()=>{if(busy){c.checked=selectedVersions.has(c.dataset.selectVersion!);return;}if(c.checked)selectedVersions.add(c.dataset.selectVersion!);else selectedVersions.delete(c.dataset.selectVersion!);render();});
 }
 let refreshTask:Promise<void>|undefined;
 async function refresh(force=false):Promise<void>{if(refreshTask){await refreshTask;if(!force)return;}refreshTask=(async()=>{try{const scoped={paginateConversions:true,includeDeletedConversions:dialog.dataset.mode==='trash',selectedVersionId:versionId||undefined,...(soundId&&data?.sounds.find(s=>s.id===soundId&&!s.deleted&&!s.purged)?.kind==='conversion'?{conversionSoundId:soundId,conversionPage,conversionPageSize:10}:{})};const next=await api.call('studio_library',scoped),sig=JSON.stringify(next);data=next;if(next.conversionPagination?.soundId===soundId)conversionPage=next.conversionPagination.page;if(force||sig!==signature){signature=sig;render();}if(dialog.open&&dialog.dataset.mode==='settings')updateEngineStatus();if(dialog.open&&dialog.dataset.mode==='compose')updateVoiceControls();if(sound()?.kind==='conversion'&&data.conversionPagination?.soundId!==soundId){signature='';queueMicrotask(()=>void refresh(true));}}catch(e){notify(`连接暂时中断：${(e as Error).message}`);}finally{}})();try{await refreshTask;}finally{refreshTask=undefined;}}
 async function blobUrl(v:Pick<StudioVersion,'audioPath'>){if(!v.audioPath)throw Error('这个版本还没有音频');return audioUrl(v.audioPath);}
 async function audioUrl(path:string){const found=cache.get(path);if(found)return found;const res=await fetch(path,{headers:{authorization:`Bearer ${api.bootstrap.token}`}});if(!res.ok)throw Error('音频暂时无法读取，请检查生成模型是否已启动');const url=URL.createObjectURL(await res.blob());cache.set(path,url);return url;}
 async function loadAudio(a:HTMLAudioElement,v:Pick<StudioVersion,'audioPath'>,play=false){const epoch=mediaEpoch;try{const url=await blobUrl(v);if(!a.isConnected||epoch!==mediaEpoch)return;a.src=url;a.onplay=()=>document.querySelectorAll<HTMLAudioElement>('audio').forEach(x=>{if(x!==a)x.pause();});if(a.id==='version-audio')$('#audio-placeholder').hidden=true;if(play)await a.play();}catch(e){notify((e as Error).message);}}
 async function saveSpeed(sourceId:string,rate:number,requestId:string){
  const saved=await api.call('studio_save_speed',{versionId:sourceId,rate,requestId});
  if(workspaceView==='project'&&versionId===sourceId){pause();versionId=saved.id;}
  await refresh(true);notify(`已保存为 V${saved.number}（${rate} 倍调速），原版保留。`);
 }
 async function download(v=version()!){const a=document.createElement('a');a.href=await blobUrl(v);const s=data.sounds.find(s=>s.id===v.soundId)!;a.download=`${s.title}-V${v.number}.${v.source.kind==='music'?'flac':'wav'}`;a.click();}
 function newProject(){dialog.dataset.mode='project';modal('新建项目',`<form id="project-form"><label for="project-name">项目名称</label><input id="project-name" required maxlength="120" placeholder="例如：春日短片"><p class="field-note">把这次创作需要的音乐、片段和旁白放在一起。</p><button class="primary" type="submit">创建项目 →</button></form>`);$<HTMLFormElement>('#project-form').onsubmit=e=>{e.preventDefault();void act(async()=>{const p=await api.call('create_project',{projectId:`project-${crypto.randomUUID()}`,title:$<HTMLInputElement>('#project-name').value});pause();workspaceView='project';projectId=p.id;soundId='';versionId='';await refresh(true);newSound();});};}
 function newSound(){dialog.dataset.mode='sound';modal('想做一个什么声音？',`<form id="sound-form"><div class="kind-options">${(['clip','music','speech','conversion'] as const).map((k,i)=>`<label><input type="radio" name="kind" value="${k}" ${i===0?'checked':''}><span><b>${kindName[k]}</b><small>${['Riff、间奏、短旋律','歌曲或纯音乐','旁白、朗读、开场白','替换人声音色，保留背景音'][i]}</small></span></label>`).join('')}</div><label for="sound-title">给这个声音起个名字</label><input id="sound-title" required maxlength="120" placeholder="例如：片头旋律"><button class="primary" type="submit">开始创作 →</button></form>`);$<HTMLFormElement>('#sound-form').onsubmit=e=>{e.preventDefault();void act(async()=>{const s=await api.call('studio_create_sound',{projectId,title:$<HTMLInputElement>('#sound-title').value,kind:$<HTMLInputElement>('[name="kind"]:checked').value as 'clip'|'music'|'speech'|'conversion'});pause();soundId=s.id;versionId='';selectedVersions.clear();await refresh(true);compose();});};}
 function voiceUploadFields(){return `<details class="reference-upload"><summary>添加参考声音</summary><label for="voice-name">音色名称</label><input id="voice-name" maxlength="120" placeholder="例如：我的旁白声音"><input id="voice-file" type="file" accept="audio/*,video/*" aria-label="参考音频"><label for="voice-start">片段起始位置（秒）</label><input id="voice-start" type="number" min="0" step="0.1" value="0"><label class="cleanup-option"><input id="voice-cleanup" type="checkbox" checked> 自动清理人声（去配乐、降噪、减弱混响）</label><p class="field-note">从指定位置取最多 15 秒，选择只有一个人说话或唱歌的片段。首次清理会下载专用模型；原音保留，完成后可以对照试听。</p><button type="button" class="secondary" data-action="upload-voice">保存到音色库</button><p id="voice-upload-progress" class="field-note" role="status"></p></details>`;}
 function renderVoiceLibrary(){
  if(!$('#voice-library')){
   $('#workspace').innerHTML=`<section id="voice-library"><header class="project-header"><div><p class="eyebrow">声音资源 · 所有项目共享</p><h1>音色库</h1><p class="library-intro">保存喜欢的参考声音，试听后用于你的下一次语音创作。</p></div><span id="voice-count" class="library-count"></span></header><div class="voice-library-layout"><section aria-label="已保存音色"><label class="voice-search-label" for="voice-search">查找音色</label><input id="voice-search" type="search" placeholder="搜索音色名称"><div id="voice-list" class="voice-list"></div></section><section class="voice-detail" aria-label="音色详情"><div id="library-voice-heading"></div><select id="voice" hidden aria-label="当前音色"></select><div id="voice-preview" class="voice-preview"></div><div id="voice-use"></div>${voiceUploadFields()}</section></div></section>`;
   $('#voice-search').oninput=()=>renderVoiceCards();
  }
  if(!voiceList().some(v=>v.id===libraryVoiceId))libraryVoiceId=voiceList()[0]?.id??'';
  const select=$<HTMLSelectElement>('#voice');
  select.innerHTML=voiceList().map(v=>`<option value="${v.id}">${esc(v.name)}</option>`).join('');select.value=libraryVoiceId;
  $('#voice-count').textContent=`${voiceList().length} 个音色${voiceList().some(v=>v.builtinId)?' · '+voiceList().filter(v=>v.builtinId).length+' 个内置':''}`;
  const v=data.voices.find(v=>v.id===libraryVoiceId),ready=!!v&&(!v.processing||v.processing.state==='succeeded');
  $('#library-voice-heading').innerHTML=v?`<p class="eyebrow">${v.builtinId?'内置音色':'参考声音'}</p><div class="entity-title"><h2>${esc(v.name)}</h2>${entityMenu('voice',v.id,'音色')}</div>`:'<h2>添加你的第一个音色</h2><p class="field-note">上传一小段人声，即可保存为可复用的参考音色。</p>';
  $('#voice-use').innerHTML=v&&sound()?.kind==='speech'?`<button class="primary" data-action="use-voice" ${ready?'':'disabled'}>用于当前语音 →</button>`:'';
  renderVoiceCards();updateVoiceControls();save();
 }
 function renderVoiceCards(){
  const query=$<HTMLInputElement>('#voice-search').value.trim().toLocaleLowerCase();
  const matches=voiceList().filter(v=>v.name.toLocaleLowerCase().includes(query));
  $('#voice-list').innerHTML=matches.map(v=>`<button class="voice-card ${v.id===libraryVoiceId?'selected':''}" data-action="select-voice" data-id="${v.id}" aria-pressed="${v.id===libraryVoiceId}"><span class="voice-card-icon" aria-hidden="true">≋</span><span class="voice-card-copy"><strong>${esc(v.name)}</strong><small>${v.builtinId?'内置音色 · ':''}${time(v.duration)} · ${v.processing?esc(v.processing.stage):'可用于语音创作'}</small></span>${v.favorite?'<span class="voice-favorite" aria-label="常用音色">★</span>':''}<span class="voice-card-arrow" aria-hidden="true">↗</span></button>`).join('')||`<div class="voice-empty"><span aria-hidden="true">≋</span><h3>${voiceList().length?'没有找到匹配的音色':'还没有音色'}</h3><p>${voiceList().length?'换个名称再找找。':'添加参考声音后，就会出现在这里。'}</p></div>`;
 }
 function openVoiceLibrary(){close();pause();workspaceView='voices';render();}
 function conversionPagination(){const p=data.conversionPagination;if(!p||p.soundId!==soundId)return '';return `<nav class="conversion-version-pagination" aria-label="转换版本分页"><button class="quiet" data-action="conversion-page" data-id="${p.page-1}" ${p.page<=1?'disabled':''}>上一页</button><span class="muted">第 ${p.page} / ${p.totalPages} 页 · 共 ${p.total} 条</span><button class="quiet" data-action="conversion-page" data-id="${p.page+1}" ${p.page>=p.totalPages?'disabled':''}>下一页</button></nav>`;}
 function composeConversion(iterate=false){
  const current=version(),sid=soundId;const source=current?.source.kind==='conversion'?current:versions().find(v=>v.source.kind==='conversion');
  const voices=data.conversionVoices.filter(v=>!v.deleted&&!v.purged&&(!v.processing||v.processing.state==='succeeded'));
  const chosen=(iterate?source?.input?.voiceId:draft().voiceId)??source?.input?.voiceId??voices[0]?.id;
  const chosenPitch=iterate?(source?.input?.pitchShiftSemitones??0):(draft().pitchShiftSemitones??source?.input?.pitchShiftSemitones??0);
  draft().pitchShiftSemitones=chosenPitch;save();
  dialog.dataset.mode='conversion';modal(`音色转换 · ${sound()!.title}`,`<form id="conversion-compose-form"><p class="form-intro">提取人声 → 转换音色 → 合回背景音。生成完整的新版本，原版保留。</p>${source?`<label class="conversion-reuse"><input type="checkbox" id="conversion-reuse" checked>沿用 V${source.number} 的原始音频</label>`:''}<div id="conversion-file-wrap" ${source?'hidden':''}><label for="conversion-source">原始音频</label><input id="conversion-source" type="file" accept=".wav,.mp3,.m4a,.flac,.aiff,.aif" ${source?'':'required'}><p class="field-note">支持 WAV、MP3、M4A、FLAC、AIFF，最大 200 MiB、最长 20 分钟。</p></div><label for="conversion-voice">目标音色</label><select id="conversion-voice" required><option value="">请选择音色</option>${voices.map(v=>`<option value="${v.id}" ${chosen===v.id?'selected':''}>${esc(v.name)}</option>`).join('')}</select><label for="conversion-pitch">整体升降调</label><select id="conversion-pitch">${Array.from({length:25},(_,i)=>i-12).map(n=>`<option value="${n}" ${n===chosenPitch?'selected':''}>${pitchLabel(n)}</option>`).join('')}</select><p class="field-note">人声、贝斯和其他伴奏同步升降调，鼓点和速度保持不变。</p><p class="field-note">沿用原录音的歌词、旋律和说话节奏。适合单人演唱或说话；多人声音会一起处理。</p><p id="conversion-submit-note" class="field-note" role="status">${esc(data.engines.conversion.message)}</p><button class="primary" id="conversion-generate" type="submit" ${data.engines.conversion.ready?'':'disabled'}>转换为新版本</button></form>`,true);
  const input=$<HTMLInputElement>('#conversion-source'),reuse=$<HTMLInputElement>('#conversion-reuse'),voice=$<HTMLSelectElement>('#conversion-voice'),pitch=$<HTMLSelectElement>('#conversion-pitch');
  if(reuse)reuse.onchange=()=>{$('#conversion-file-wrap').hidden=reuse.checked;input.required=!reuse.checked;};
  voice.onchange=()=>{draft().voiceId=voice.value;save();};
  pitch.onchange=()=>{draft().pitchShiftSemitones=Number(pitch.value);save();};
  $<HTMLFormElement>('#conversion-compose-form').onsubmit=e=>{e.preventDefault();void act(async()=>{
   const selected=voice.value,pitchShiftSemitones=Number(pitch.value),file=input.files?.[0],reusing=!!reuse?.checked;if(!Number.isInteger(pitchShiftSemitones)||pitchShiftSemitones < -12||pitchShiftSemitones > 12)throw Error('升降调应在 -12 到 12 半音之间');if(!selected)throw Error('请选择目标音色');if(!reusing&&!file)throw Error('请选择原始音频');if(file&&!reusing&&file.size>200*1024*1024)throw Error('音频超过 200 MiB');
   const requestKey=JSON.stringify([selected,pitchShiftSemitones,reusing?source?.source.id:[file?.name,file?.size,file?.lastModified]]);let request=conversionRequests.get(sid);if(request?.key!==requestKey){request={key:requestKey,id:crypto.randomUUID()};conversionRequests.set(sid,request);}
   const submit=$<HTMLButtonElement>('#conversion-generate');submit.disabled=true;$('#conversion-submit-note').textContent=reusing?'正在提交…':'正在上传完整音频…';
   try{let job:{id:string};if(reusing){job=await api.call('svc_create_version',{soundId:sid,sourceJobId:source!.source.id,voiceId:selected,pitchShiftSemitones,requestId:request.id});}else{const query=new URLSearchParams({soundId:sid,name:file!.name,voiceId:selected,pitchShiftSemitones:String(pitchShiftSemitones),requestId:request.id,...(source?{parentId:source.id}:{})});const response=await fetch(`/conversion/upload?${query}`,{method:'POST',headers:{authorization:`Bearer ${api.bootstrap.token}`,'content-type':'application/octet-stream'},body:file});const result=await response.json();if(!response.ok)throw Error(result.message??'上传失败，请重试');job=result;}
    conversionRequests.delete(sid);pause();versionId=job.id;conversionPage=1;close();await refresh(true);notify('已提交完整音频转换，完成后保存在当前片段。');
   }finally{submit.disabled=false;}
  });};
 }
 async function conversionAudio(action:string){const v=version();if(!v||v.source.kind!=='conversion')return;$('.more-menu')?.removeAttribute('open');const original=action.includes('-original-'),path=`/conversion/audio/${encodeURIComponent(v.source.id)}/${original?'original':'vocals'}`,label=original?'原音':'转换人声';
  if(action.endsWith('-download')){const link=document.createElement('a');link.href=await audioUrl(path);link.download=`${sound()!.title}-V${v.number}-${label}${original&&v.input?.text?.match(/\.[^.]+$/)?v.input.text.match(/\.[^.]+$/)![0]:'.wav'}`;link.click();return;}
  pause();dialog.dataset.mode='conversion-audio';modal(`V${v.number} · ${label}`,'<audio id="conversion-part-audio" controls></audio>');void loadAudio($<HTMLAudioElement>('#conversion-part-audio'),{audioPath:path},true);
 }
 function compose(iterate=false){const s=sound()!;if(s.kind==='conversion'){composeConversion(iterate);return;}if(iterate&&version()){drafts[s.id]=versionCreationDraft(s.id,version()!.id,version()!.input);save();}if(draft().parentId&&data.versions.find(v=>v.id===draft().parentId)?.deleted)delete draft().parentId;const d=draft();if(d.voiceId&&!voiceList().some(v=>v.id===d.voiceId))d.voiceId='';const speech=s.kind==='speech',ready=speech?data.engines.speech.canGenerate:data.engines.music.canGenerate;dialog.dataset.mode='compose';
 modal(`${versions().length?'再创作一版':'开始创作'} · ${s.title}`,`<form id="compose-form"><p class="form-intro">${d.parentId?`从 V${data.versions.find(v=>v.id===d.parentId)?.number??'?'} 的要求继续修改，原版会保留。`:'先把想法说清楚，听过以后再慢慢调整。'}</p>
 ${speech?`<section class="form-group"><h3 class="form-group-title">参考声音</h3><label class="sr-only" for="voice">参考声音</label><select id="voice" required><option value="" ${!d.voiceId?'selected':''}>${voiceList().length?'请选择音色':'请先添加参考声音'}</option>${voiceList().map(v=>`<option value="${v.id}" ${d.voiceId===v.id?'selected':''}>${v.favorite?'★ ':''}${esc(v.name)}${v.processing&&v.processing.state!=='succeeded'?' · '+esc(v.processing.stage):''}</option>`).join('')}</select><div id="voice-preview" class="voice-preview"></div>${voiceUploadFields()}</section>`:`<section class="form-group"><h3 class="form-group-title">作品形式</h3><fieldset class="music-mode"><legend class="sr-only">作品形式</legend><label><input type="radio" name="instrumental" value="true" ${d.instrumental!==false?'checked':''}> 纯音乐</label><label><input type="radio" name="instrumental" value="false" ${d.instrumental===false?'checked':''}> 带人声</label></fieldset></section>`}
 <section class="form-group"><h3 class="form-group-title">${speech?'要说的话':'想要什么声音？'}</h3><label class="sr-only" for="creation-text">${speech?'要说的话':'想要什么声音？'}</label><textarea id="creation-text" rows="${speech?2:3}" required maxlength="8000" placeholder="${speech?'写下要朗读的正文…':'描述氛围、乐器和用途，例如：一段温暖的钢琴 riff，用作春日短片的开场。'}">${esc(d.text)}</textarea></section>
 ${speech?`<section class="form-group"><h3 class="form-group-title">情绪</h3><label class="sr-only" for="emotion-strength">情绪强度</label><select id="emotion-strength">${emotionStrengths.map(tier=>`<option value="${tier}" ${displayedEmotionStrength(d)===tier?'selected':''}>${emotionStrengthLabels[tier]}</option>`).join('')}</select><p class="field-note">调节情绪表现的程度。描述留空时，调节参考人声的情绪影响。</p><details class="advanced" ${d.emotion?'open':''}><summary>情绪描述（可选）</summary><textarea id="emotion" rows="2" maxlength="2000" placeholder="例如：平静，带一点期待">${esc(d.emotion??'')}</textarea></details></section>`:`<section class="form-group" id="lyrics-wrap" ${d.instrumental===false?'':'hidden'}><h3 class="form-group-title">歌词</h3><label class="sr-only" for="lyrics">歌词</label><textarea id="lyrics" rows="5" maxlength="16000" placeholder="[verse]&#10;填写歌词…">${esc(d.lyrics??'')}</textarea></section><details class="advanced"><summary>生成偏好</summary><label for="preset">生成方式</label><select id="preset"><option value="fast" ${d.preset!=='quality'?'selected':''}>较快尝试</option><option value="quality" ${d.preset==='quality'?'selected':''}>更精细</option></select><p class="field-note">可在描述中写下期望时长；实际长度由模型生成。</p></details>`}
 <div class="compose-bottom"><span id="generation-readiness" class="muted">${ready?(speech?'IndexTTS 2.0':'YuE2')+' 已就绪':(speech?'语音':'音乐')+'模型尚未准备好'}</span>${ready?`<button id="generate" class="primary" type="submit">生成新版本 →</button>`:'<button class="secondary" type="button" data-action="settings">准备生成模型 →</button>'}</div><p class="field-note">生成可能需要几分钟。关掉这个窗口后，任务会继续。</p></form>`,true);
 const form=$<HTMLFormElement>('#compose-form');const updateDraft=(e:Event)=>{d.text=$<HTMLTextAreaElement>('#creation-text').value;if(speech){d.voiceId=$<HTMLSelectElement>('#voice').value;d.emotion=$<HTMLTextAreaElement>('#emotion').value;if((e.target as HTMLElement)?.id==='emotion-strength')d.emotionStrength=$<HTMLSelectElement>('#emotion-strength').value as EmotionStrength;if(d.emotionStrength===undefined)$<HTMLSelectElement>('#emotion-strength').value=displayedEmotionStrength(d);}else{d.instrumental=$<HTMLInputElement>('[name="instrumental"]:checked').value==='true';d.lyrics=$<HTMLTextAreaElement>('#lyrics').value;d.preset=$<HTMLSelectElement>('#preset').value as 'fast'|'quality';$('#lyrics-wrap').hidden=d.instrumental;}save();if(speech)updateVoiceControls();};form.oninput=updateDraft;form.onchange=updateDraft;
 form.onsubmit=e=>{e.preventDefault();void act(async()=>{const submitted=structuredClone(d);if(!speech)delete submitted.emotionStrength;if(speech){const voice=data.voices.find(v=>v.id===submitted.voiceId);if(!voice||voice.deleted||voice.processing&&voice.processing.state!=='succeeded')throw Error('参考人声还未清理完成，请等待或重试');}if(!speech&&submitted.instrumental===false&&!submitted.lyrics?.trim())throw Error('请填写歌词');const v=await api.call('studio_generate',submitted);pause();versionId=v.id;close();await refresh(true);notify(v.state==='failed'?v.error??'提交失败':'已开始生成，完成后会出现在这个声音里。');});};if(speech)updateVoiceControls();
 }
 function updateVoiceControls(){
  const select=$<HTMLSelectElement>('#voice'),preview=$('#voice-preview');if(!select||!preview)return;
  const v=voiceList().find(v=>v.id===select.value),p=v?.processing,canUse=!!v&&(!p||p.state==='succeeded');
  const generate=$<HTMLButtonElement>('#generate');if(generate)generate.disabled=!canUse;
  const sig=JSON.stringify(v);if(preview.dataset.signature===sig)return;preview.dataset.signature=sig;
  const selected=select.value;select.innerHTML='<option value="">请选择音色</option>'+voiceList().map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${x.favorite?'★ ':''}${esc(x.name)}${x.processing&&x.processing.state!=='succeeded'?' · '+esc(x.processing.stage):''}</option>`).join('')||'<option value="">请先添加参考声音</option>';
  preview.querySelectorAll('audio').forEach(a=>a.pause());
  if(!v){preview.innerHTML='<p class="field-note">保存的音色可在所有项目中重复使用。</p>';return;}
  const audio=(original=false)=>`<div class="voice-sample"><span>${original?'原音':p?'处理后人声':'已保存音色'}</span><audio controls preload="metadata" data-voice-audio="${v.id}" data-original="${original}" aria-label="${esc(v.name)} · ${original?'原音':p?'处理后人声':'试听'}"></audio></div>`;
  preview.innerHTML=`<div class="voice-preview-actions"><span class="muted">${time(v.duration)} · 所有项目可用</span><button type="button" class="quiet" data-action="favorite-voice" data-id="${v.id}" aria-pressed="${!!v.favorite}">${v.favorite?'★ 常用音色':'☆ 设为常用'}</button></div>${p?audio(true):''}${canUse?audio():`<p class="field-note" role="status">${esc(p!.stage)}${p!.error?'：'+esc(p!.error):''}</p>`}${!p||['failed','interrupted'].includes(p.state)?`<button type="button" class="secondary" data-action="clean-voice" data-id="${v.id}">${p?'重试人声清理':'清理这个音色'}</button>`:''}`;
  preview.querySelectorAll<HTMLAudioElement>('audio').forEach(a=>void loadAudio(a,{audioPath:`/speech/voice-audio/${v.id}${a.dataset.original==='true'?'?original=true':''}`}));
 }
 async function uploadVoice(){
  const file=$<HTMLInputElement>('#voice-file').files?.[0],name=$<HTMLInputElement>('#voice-name').value.trim(),sid=soundId,cleanup=$<HTMLInputElement>('#voice-cleanup').checked,start=Number($<HTMLInputElement>('#voice-start').value);
  if(!file||!name)throw Error('请填写名称并选择参考音频');if(!Number.isFinite(start)||start<0)throw Error('片段起始位置需要是大于或等于 0 的秒数');if(file.size>50*1024*1024)throw Error('参考文件不能超过 50 MiB');
  $('#voice-upload-progress').textContent='正在读取参考片段…';
  const context=new AudioContext();let decoded:AudioBuffer;try{decoded=await context.decodeAudioData(await file.arrayBuffer());}catch{throw Error('浏览器无法读取这个文件的声音，请先导出为 WAV、MP3 或 M4A 再上传');}finally{await context.close();}
  const duration=Math.min(15,decoded.duration-start);if(duration<.3)throw Error('请调整起始位置，至少保留 0.3 秒参考人声');
  const channels=Math.min(2,decoded.numberOfChannels),offline=new OfflineAudioContext(channels,Math.ceil(duration*44100),44100),source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start(0,start,duration);
  const pcm=await offline.startRendering(),bytes=encodeWav(Array.from({length:channels},(_,i)=>pcm.getChannelData(i)),44100);
  const res=await fetch('/speech/voices?name='+encodeURIComponent(name)+'&cleanup='+cleanup,{method:'POST',headers:{authorization:`Bearer ${api.bootstrap.token}`,'content-type':'audio/wav'},body:bytes}),voice=await res.json();if(!res.ok)throw Error(voice.message);
  if(dialog.open&&dialog.dataset.mode==='compose'&&sid)(drafts[sid]??(drafts[sid]={soundId:sid,text:''})).voiceId=voice.id;libraryVoiceId=voice.id;save();await refresh(true);if(workspaceView==='voices'){$<HTMLInputElement>('#voice-name').value='';$<HTMLInputElement>('#voice-file').value='';$('#voice-upload-progress').textContent='音色已保存。';}if(dialog.open&&dialog.dataset.mode==='compose'&&soundId===sid)compose();notify(cleanup?'已保存原音，后台正在清理人声。':'音色已保存，所有项目都可复用。');
 }

 function settings(){dialog.dataset.mode='settings';modal('设置',`<section class="settings-section"><h3>生成模型</h3><div class="engine-row"><div><b>语音 · IndexTTS 2.0</b><p id="tts-status"></p></div><button class="secondary" data-action="prepare-speech">准备模型</button></div><div class="engine-row"><div><b>音乐 · YuE2</b><p id="music-status"></p></div><button class="secondary" data-action="start-music">启动</button></div><div class="engine-row"><div><b>音色转换 · Seed-VC</b><p id="conversion-status"></p><p id="conversion-models" class="field-note"></p></div></div><details class="advanced"><summary>安装与诊断</summary><label for="tts-directory">语音模型目录</label><input id="tts-directory" value="${esc(data.engines.speech.directory)}"><label for="music-directory">音乐模型目录</label><input id="music-directory" value="${esc(data.engines.music.directory??data.engines.music.defaultDirectory)}"><button class="secondary" data-action="prepare-music">安装音乐模型</button><button class="quiet" data-action="stop-music">停止音乐服务</button><button class="quiet" data-action="cancel-preparation">取消语音准备</button><p class="field-note">音色转换模型目录</p><p id="conversion-directory" class="path"></p><pre id="engine-logs"></pre></details></section><section class="settings-section"><h3>本地文件与 Agent</h3><p class="path">${esc(api.bootstrap.workspace)}</p><button class="secondary" data-action="copy-mcp">复制 Agent 连接配置</button><a class="text-link" href="./credits.html">开源许可 ↗</a></section>`);updateEngineStatus();}
 function updateEngineStatus(){if(!$('#tts-status'))return;$('#tts-status').textContent=data.engines.speech.message;$('#music-status').textContent=data.engines.music.message;const conversion=data.engines.conversion;$('#conversion-status').textContent=conversion.message;$('#conversion-models').textContent=[conversion.model,conversion.backend,conversion.separationModel?`人声分离：${conversion.separationModel}`:undefined].filter(Boolean).join(' · ');$('#conversion-directory').textContent=conversion.directory??'尚未配置';$('#engine-logs').textContent=[...data.engines.speech.logs.slice(-5),...data.engines.music.logs.slice(-5)].join('\n');}
 function tools(){dialog.dataset.mode='tools';modal('导入与 Agent 创作',`<p class="form-intro">结果会作为「${esc(sound()!.title)}」的新版本保存。</p>${sound()!.kind!=='speech'?'<button class="secondary" data-action="import">导入 MIDI / 乐谱 JSON</button><p class="field-note">MIDI 导入后使用乐器音源合成，可以试听并继续编辑。</p>':''}<button class="secondary" data-action="agent">复制给 Agent 的创作要求</button><p class="field-note">包含项目、声音和来源版本。复制后交给你的 Agent，不会在这里自动发起任务。</p>`);}
 async function compare(){if(selectedVersions.size!==2||versions().filter(v=>selectedVersions.has(v.id)).some(v=>!v.audioPath))return;pause();dialog.dataset.mode='compare';const vs=[...selectedVersions].map(id=>data.versions.find(v=>v.id===id)!);modal('听听哪一版更合适',`<p class="field-note">分别试听，播放另一版时会暂停当前版。</p>${vs.map(v=>`<section class="compare-item"><h3>V${v.number}${v.voiceName?' · '+esc(v.voiceName):''}</h3><audio controls data-comparison="${v.id}"></audio></section>`).join('')}`,true);for(const v of vs)void loadAudio($<HTMLAudioElement>(`[data-comparison="${v.id}"]`),v);}
 async function changeDeletedVersions(ids:string[],deleted:boolean){
  if(!ids.length)return;
  const changed:string[]=[],failures:string[]=[];
  for(const id of ids){try{await api.call('studio_update_version',{versionId:id,deleted});changed.push(id);if(deleted)selectedVersions.delete(id);}catch(e){failures.push((e as Error).message);}}
  if(deleted&&changed.includes(versionId))pause();
  await refresh(true);
  const message=changed.length?(deleted?`${changed.length} 个版本已移入回收站。`:`已恢复 ${changed.length} 个版本。`):'';
  notify(message+(failures.length?` ${failures.length} 个版本${deleted?'删除':'恢复'}失败：${failures[0]}`:''),deleted&&changed.length?()=>changeDeletedVersions(changed,false):undefined);
 }
 type EntityKind='project'|'sound'|'version'|'voice';
 function entityBusy(kind:EntityKind,id:string){if(kind==='voice'){const v=data.voices.find(v=>v.id===id);return ['queued','running'].includes(v?.processing?.state??'')||data.versions.some(v=>v.input?.voiceId===id&&!selectable(v));}const ids=kind==='project'?data.sounds.filter(s=>s.projectId===id).map(s=>s.id):[id];return data.versions.some(v=>ids.includes(v.soundId)&&!selectable(v));}
 function entityMenu(kind:EntityKind,id:string,label:string){const disabled=entityBusy(kind,id);return `<details class="entity-menu" data-entity-kind="${kind}" data-id="${id}"><summary aria-label="${label}更多操作">•••</summary><div><button data-action="rename-entity" data-kind="${kind}" data-id="${id}">重命名${label}</button><button class="danger" data-action="delete-entity" data-kind="${kind}" data-id="${id}" ${disabled?'disabled title="请先取消或等待生成完成"':''}>删除${label}</button>${disabled?'<p class="field-note">请先取消或等待生成完成。</p>':''}</div></details>`;}
 function entityInfo(kind:EntityKind,id:string){const p=data.projects.find(p=>p.id===id),s=data.sounds.find(s=>s.id===id),v=data.versions.find(v=>v.id===id),voice=data.voices.find(v=>v.id===id);if(kind==='project'){const children=data.sounds.filter(s=>s.projectId===id);return {title:p!.title,label:'项目',detail:`包含 ${children.length} 个片段、${data.versions.filter(v=>children.some(s=>s.id===v.soundId)).length} 个版本。`};}if(kind==='sound')return {title:s!.title,label:'片段',detail:`包含 ${data.versions.filter(v=>v.soundId===id).length} 个版本。`};if(kind==='voice')return {title:voice!.name,label:'音色',detail:'已生成的音频和历史音色名称保留。'};return {title:`${data.sounds.find(s=>s.id===v!.soundId)?.title} · V${v!.number}`,label:'版本',detail:'其他版本保留。'};}
 function clearDeletedSelection(kind:EntityKind,id:string){if(kind==='project'&&id===projectId){projectId='';soundId='';versionId='';conversionPage=1;selectedVersions.clear();}else if(kind==='sound'&&id===soundId){soundId='';versionId='';conversionPage=1;selectedVersions.clear();}else if(kind==='version'&&id===versionId)versionId='';}
 async function updateEntity(kind:EntityKind,id:string,deleted:boolean){const result=kind==='project'?await api.call('studio_update_project',{projectId:id,deleted}):kind==='sound'?await api.call('studio_update_sound',{soundId:id,deleted}):kind==='voice'?await api.call('tts_update_voice',{voiceId:id,deleted}):await api.call('studio_update_version',{versionId:id,deleted});if(deleted)clearDeletedSelection(kind,id);return result;}
 function confirmEntity(kind:EntityKind,id:string,purge=false){const info=entityInfo(kind,id);dialog.dataset.mode='entity-confirm';modal(`${purge?'彻底删除':'删除'}${info.label}`,`<p class="requirement-text">${purge?'彻底删除':'将'}「${esc(info.title)}」${purge?'？':'移入回收站？'}</p><p class="field-note">${esc(info.detail)}</p><p class="field-note">${purge?'保存的文件将被删除，此操作不可恢复。':kind==='project'||kind==='sound'?'所属内容一起移入回收站，恢复时保留原状态。':'可在回收站恢复。'}</p><div class="confirm-actions"><button class="secondary" data-action="close">取消</button><button class="secondary danger" data-action="${purge?'confirm-purge':'confirm-delete'}" data-kind="${kind}" data-id="${id}">${purge?'彻底删除':'移入回收站'}</button></div>`);}
 function renameEntity(kind:EntityKind,id:string){const info=entityInfo(kind,id);dialog.dataset.mode='rename';modal(`重命名${info.label}`,`<form id="rename-form"><label for="entity-name">${info.label}名称</label><input id="entity-name" required maxlength="120" value="${esc(info.title)}"><button class="primary" type="submit">保存</button></form>`);$<HTMLFormElement>('#rename-form').onsubmit=e=>{e.preventDefault();void act(async()=>{const title=$<HTMLInputElement>('#entity-name').value;if(kind==='project')await api.call('studio_update_project',{projectId:id,title});else if(kind==='sound')await api.call('studio_update_sound',{soundId:id,title});else await api.call('tts_update_voice',{voiceId:id,name:title});close();await refresh(true);notify('名称已更新。');});};}
 function trash(){dialog.dataset.mode='trash';const projectDeleted=(id:string)=>!!data.projects.find(p=>p.id===id)?.deleted;const soundDeleted=(id:string)=>{const s=data.sounds.find(s=>s.id===id);return !s||!!s.deleted||projectDeleted(s.projectId);};const entries:{kind:EntityKind;id:string}[]=[...data.projects.filter(p=>p.deleted).map(p=>({kind:'project' as const,id:p.id})),...data.sounds.filter(s=>s.deleted&&!projectDeleted(s.projectId)).map(s=>({kind:'sound' as const,id:s.id})),...data.versions.filter(v=>v.deleted&&!soundDeleted(v.soundId)).map(v=>({kind:'version' as const,id:v.id})),...data.voices.filter(v=>v.deleted).map(v=>({kind:'voice' as const,id:v.id}))];modal('回收站',`<p class="field-note">所有项目、片段、版本和音色。恢复整个项目或片段时，保留其删除前的版本状态和成品选择。</p>${entries.map(({kind,id})=>{const info=entityInfo(kind,id);return `<div class="trash-row"><div><small class="muted">${info.label}</small><p>${esc(info.title)}</p></div><div class="trash-actions"><button class="secondary" data-action="${kind==='version'?'restore':'restore-entity'}" data-kind="${kind}" data-id="${id}">恢复</button><button class="quiet danger" data-action="purge-entity" data-kind="${kind}" data-id="${id}">彻底删除</button></div></div>`;}).join('')||'<p>回收站是空的。</p>'}`,true);}
 document.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id,kind=b.dataset.kind as EntityKind;if(action==='delete-entity'||action==='purge-entity'){b.closest('details')?.removeAttribute('open');confirmEntity(kind,id!,action==='purge-entity');return;}if(action==='rename-entity'){b.closest('details')?.removeAttribute('open');renameEntity(kind,id!);return;}const immediate:Record<string,()=>void>={close,newProject,'new-project':newProject,'new-sound':newSound,compose:()=>compose(),iterate:()=>compose(true),'voice-library':openVoiceLibrary,settings,tools,trash:()=>void act(async()=>{dialog.dataset.mode='trash';await refresh(true);trash();})};if(action&&immediate[action]){immediate[action]();return;}void act(async()=>{
  if(action==='confirm-delete'){pause();await updateEntity(kind,id!,true);close();await refresh(true);notify('已移入回收站。',async()=>{await updateEntity(kind,id!,false);await refresh(true);});}
  else if(action==='confirm-purge'){await api.call('studio_purge',{kind,id:id!});clearDeletedSelection(kind,id!);pause();for(const url of cache.values())URL.revokeObjectURL(url);cache.clear();close();await refresh(true);trash();notify('已彻底删除。');}
  else if(action==='restore-entity'){await updateEntity(kind,id!,false);if(kind==='project'){projectId=id!;soundId='';versionId='';}if(kind==='sound'){soundId=id!;projectId=data.sounds.find(s=>s.id===id)!.projectId;versionId='';}await refresh(true);trash();notify('已恢复。');}
  else if(action==='conversion-page'){conversionPage=Number(id);selectedVersions.clear();await refresh(true);}
  else if(action?.startsWith('conversion-')){await conversionAudio(action);}
  else if(action==='project'||action==='sound'||action==='version'){pause();workspaceView='project';if(action!=='version'){selectedVersions.clear();conversionPage=1;}if(action==='project'){projectId=id!;soundId='';versionId='';}else if(action==='sound'){soundId=id!;versionId='';}else versionId=id!;if(action!=='version')await refresh(true);else render();}
  else if(action==='select-voice'){libraryVoiceId=id!;renderVoiceLibrary();}
  else if(action==='use-voice'){draft().voiceId=libraryVoiceId;workspaceView='project';pause();render();compose();}
  else if(action==='select-all'){selectedVersions=new Set(versions().filter(selectable).map(v=>v.id));render();}
  else if(action==='clear-selection'){selectedVersions.clear();render();}
  else if(action==='delete-selected')await changeDeletedVersions([...selectedVersions],true);
  else if(action==='delete')await changeDeletedVersions([versionId],true);
  else if(action==='final'||action==='keep'){const v=version()!;await api.call('studio_update_version',{versionId:v.id,...(action==='final'?{final:sound()!.finalVersionId!==v.id}:{kept:!v.kept})});await refresh(true);}
  else if(action==='restore'){await api.call('studio_update_version',{versionId:id!,deleted:false});await refresh(true);trash();}
  else if(action==='cancel'){await api.call('studio_cancel',{versionId:versionId});await refresh(true);}
  else if(action==='render'){autoplayId=versionId;await api.call('studio_render',{versionId});await refresh(true);}
  else if(action==='download')await download(id?data.versions.find(v=>v.id===id)!:version()!);
  else if(action==='compare')await compare();
  else if(action==='upload-voice')await uploadVoice();
  else if(action==='favorite-voice'){const v=data.voices.find(v=>v.id===id)!;await api.call('tts_update_voice',{voiceId:v.id,favorite:!v.favorite});await refresh(true);}
  else if(action==='clean-voice'){const sid=soundId,v=await api.call('tts_clean_voice',{voiceId:id!});if(dialog.open&&dialog.dataset.mode==='compose'&&sid)draft().voiceId=v.id;libraryVoiceId=v.id;save();await refresh(true);if(dialog.open&&dialog.dataset.mode==='compose'&&soundId===sid)compose();}
  else if(action==='requirements'){dialog.dataset.mode='requirements';const v=version()!;modal(`V${v.number} · 创作要求`,`${v.voiceName?`<p class="field-note">音色：${esc(v.voiceName)}</p>`:''}<p class="requirement-text">${esc(v.input?.text??'这份历史记录未保存创作要求。')}</p>${v.source.kind==='speech'?`<p class="field-note">情绪强度：${emotionStrengthLabels[displayedEmotionStrength(v.input??{})]}</p>`:''}${v.input?.emotion?`<h3>情绪</h3><p>${esc(v.input.emotion)}</p>`:''}${v.input?.lyrics?`<h3>歌词</h3><pre>${esc(v.input.lyrics)}</pre>`:''}`);}
  else if(action==='deliverables'){dialog.dataset.mode='deliverables';modal('项目成品',sounds().filter(s=>s.finalVersionId).map(s=>{const v=data.versions.find(v=>v.id===s.finalVersionId)!;return `<div class="trash-row"><span>${esc(s.title)} · V${v.number}</span>${v.audioPath?`<button class="secondary" data-action="download" data-id="${v.id}">下载</button>`:'<span>需先生成试听音频</span>'}</div>`;}).join('')||'<p>试听后，把满意的版本选为成品，它就会出现在这里。</p>');}
  else if(action==='prepare-speech'){await api.call('tts_prepare',{directory:$<HTMLInputElement>('#tts-directory').value});await refresh(true);notify('已开始准备语音模型。');}
  else if(action==='start-music'){await api.call('start_yue2',{});await refresh(true);}
  else if(action==='prepare-music'){await api.call('prepare_yue2',{directory:$<HTMLInputElement>('#music-directory').value,downloadModels:true});await refresh(true);}
  else if(action==='stop-music'){await api.call('stop_yue2',{});await refresh(true);}
  else if(action==='cancel-preparation'){await api.call('tts_cancel_preparation',{});await refresh(true);}
  else if(action==='copy-mcp'){await navigator.clipboard.writeText(JSON.stringify(api.bootstrap.mcp,null,2));notify('Agent 连接配置已复制。');}
  else if(action==='agent'){const s=sound()!,v=version();await navigator.clipboard.writeText(`请为项目「${project()!.title}」中的「${s.title}」创作${kindName[s.kind]}。项目 ID: ${projectId}，声音 ID: ${soundId}。${v?'来源版本 ID: '+v.id:''}\n要求：${draft().text||v?.input?.text||'请先与我确认创作要求。'}\n使用 Music Room MCP 读取 studio_library 获取完整上下文。模型生成调用 studio_generate 并指定 soundId。交付乐谱则通过 get_authoring_context 获取格式，并用 studio_import_score 写入这个 soundId，parentId 指向来源版本。不要创建无关项目或覆盖旧版。`);notify('已复制当前声音的创作要求。');}
  else if(action==='import'){$<HTMLInputElement>('#score-file').click();}
  else if(action==='midi'){const v=version()!,doc=await api.call('get_revision',{projectId:v.source.projectId!,revisionId:v.source.id}),{scoreToMidi}=await import('../../midi.ts');const a=document.createElement('a'),url=URL.createObjectURL(new Blob([new Uint8Array(scoreToMidi(doc.composition.score))],{type:'audio/midi'}));a.href=url;a.download=`${sound()!.title}-V${v.number}.mid`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 });});
 $<HTMLInputElement>('#score-file').onchange=e=>{const file=(e.target as HTMLInputElement).files?.[0],sid=soundId,parentId=version()?.id;(e.target as HTMLInputElement).value='';if(!file)return;void act(async()=>{if(file.size>4*1024*1024)throw Error('乐谱文件不能超过 4 MiB');let json:string;if(/\.midi?$/i.test(file.name)){const {midiToComposition}=await import('../../music/import/midi.ts');json=JSON.stringify(midiToComposition(new Uint8Array(await file.arrayBuffer()),file.name,`midi-${crypto.randomUUID()}`));}else json=await file.text();const v=await api.call('studio_import_score',{soundId:sid,compositionJson:json,parentId});pause();versionId=v.id;close();await refresh(true);notify('已导入为新版本。');});};
 await refresh(true);setInterval(()=>void refresh(),1800);window.addEventListener('beforeunload',()=>{for(const url of cache.values())URL.revokeObjectURL(url);});
}
