import type {ResourceStatus} from '../../service/operations.ts';
export const resourceEngineNames:Record<string,string>={tts:'语音',reference:'参考清理',conversion:'音色转换',yue2:'音乐',render:'乐谱合成',speed:'调速',installation:'安装准备'};
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const gib=(bytes:number)=>`${(bytes/2**30).toFixed(1)} GiB`;
const stages:Record<string,string>={queued:'排队中',waiting_resources:'等待资源',loading:'加载中',running:'处理中',cancelling:'正在取消',succeeded:'完成',blocked:'已阻止',failed:'失败',cancelled:'已取消'};
export function resourcePanel(status:ResourceStatus){
 const hardware=status.hardware,policy=status.policy,tasks=[...(status.active?[status.active]:[]),...status.queued];
 const pools=hardware?.pools.map(p=>{const reserve=Math.max(policy.reserveMinimum,Math.ceil(p.capacity*policy.reserveFraction)),limit=Math.max(0,Math.min(p.capacity-reserve,p.platformLimit??p.capacity,policy.limits?.[p.id]??p.capacity));return `<p>${hardware.topology==='unified'?'共享内存':p.id==='memory'?'系统内存':escape(p.id)}：${gib(p.capacity)} · 应用上限 ${gib(limit)}<br><span class="field-note">可用估计 ${gib(p.available)} · 为系统保留 ${gib(reserve)}</span></p>`;}).join('')??'<p>电脑资源暂时无法读取</p>';
 const pressure={normal:'正常',warning:'偏高，后续任务等待',critical:'过高，停止重型任务',unknown:'暂时无法读取'};
 const usage=status.active&&status.observation?`<p class="field-note">当前任务采样 ${Object.values(status.observation.usage).map(gib).join(' / ')} · 预约 ${Object.values(status.reservations).map(gib).join(' / ')}（采样保护并非瞬时硬上限）</p>`:'';
 return `<p class="field-note">模型驻留：${status.residents.length?status.residents.map(r=>escape(resourceEngineNames[r.engine]??r.engine)).join('、'):'无'}</p>${pools}${hardware?`<p class="field-note">内存压力：${pressure[hardware.pressure]} · 采样 ${escape(new Date(hardware.sampledAt).toLocaleTimeString())}</p>`:''}${usage}${status.fault||status.configurationError?`<p role="alert">${escape(status.fault?.message??status.configurationError)}</p>`:''}<div class="resource-actions"><button class="secondary" data-action="resource-pause">${status.paused?'恢复后续任务':'暂停后续任务'}</button><button class="quiet" data-action="resource-release" ${tasks.length?'disabled':''}>释放空闲模型</button></div><p class="field-note">${status.paused?'后续任务已暂停，当前任务继续。':'重型任务逐项执行，结束后释放模型。'} 已有作品可随时浏览和播放。</p><div class="resource-tasks">${tasks.length?tasks.map(t=>`<div class="resource-task"><div><b>${escape(resourceEngineNames[t.engine]??t.engine)}</b><p>${escape(t.message??stages[t.stage]??t.stage)}</p></div><button class="quiet" data-action="resource-cancel" data-id="${escape(t.id)}">取消</button></div>`).join(''):'<p>当前没有重型任务</p>'}</div>${status.history.slice(-3).reverse().map(t=>`<p class="field-note">${escape(resourceEngineNames[t.engine]??t.engine)} · ${escape(t.message??stages[t.stage])}</p>`).join('')}<p class="field-note">已验证输入范围：语音最多 140 字，参考音频 15 秒；音乐风格 1000 字、歌词 2000 字。能否运行还取决于本机容量和当前压力。</p>`;
}
