import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {createServer} from 'vite';
import {chromium} from 'playwright';
import {encodeWav} from '../src/wav.ts';

test('conversion belongs to a project sound, has paged versions and reuses source with another voice',async()=>{
 const wav=Buffer.from(encodeWav([Float32Array.from({length:24000*8},(_,i)=>Math.sin(i*.1)*.2)],24000));
 const sounds=[{id:'speech',projectId:'p',title:'旁白',kind:'speech'}],versions=[];let uploads=0,reused=0;const pages=[],pitchRequests=[];
 const voices=[{id:'gong',name:'龚琳娜',duration:15},{id:'other',name:'另一音色',duration:10}];
 const server=await createServer({server:{port:0,host:'127.0.0.1'},plugins:[{name:'bootstrap',transformIndexHtml(html){return html.replace('</head>','<script id="music-room-service" type="application/json">{"token":"test-token","url":"/","workspace":"conversion-ui-test"}</script></head>');}}]});await server.listen();
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const add=(id,voiceId='gong',pitchShiftSemitones=0)=>{const v={id,soundId:'conv',number:versions.length+1,createdAt:new Date(Date.now()+versions.length*1000).toISOString(),state:'succeeded',stage:'转换完成',kept:false,deleted:false,voiceName:voices.find(v=>v.id===voiceId).name,input:{soundId:'conv',voiceId,pitchShiftSemitones,text:'完整歌曲.wav'},source:{kind:'conversion',id},audioPath:`/conversion/audio/${id}/converted`};versions.push(v);return v;};
 await page.route('**/api/**',async route=>{const op=new URL(route.request().url()).pathname.split('/').pop(),args=route.request().postDataJSON();let result={};
  if(op==='studio_library'){assert.equal(args.paginateConversions,true);if(args.conversionSoundId)assert.equal(!!sounds.find(s=>s.id===args.conversionSoundId)?.deleted,false,'deleted sound must not remain the pagination scope');const scoped=versions.filter(v=>!v.deleted).toReversed(),number=Math.min(args.conversionPage??1,Math.max(1,Math.ceil(scoped.length/10))),items=scoped.slice((number-1)*10,number*10);pages.push(args);result={projects:[{id:'p',title:'测试短片'}],sounds,versions:[...new Map([...items,...versions.filter(v=>v.id===args.selectedVersionId||sounds.some(s=>s.finalVersionId===v.id))].map(v=>[v.id,v])).values()],voices,conversionVoices:voices,engines:{speech:{canGenerate:true,logs:[]},music:{canGenerate:false,logs:[]},conversion:{ready:true,message:'可以开始转换'}},conversionPagination:{soundId:args.conversionSoundId,page:number,pageSize:10,total:scoped.length,totalPages:Math.max(1,Math.ceil(scoped.length/10)),versionIds:items.map(v=>v.id)}};}
  if(op==='studio_create_sound'){assert.equal(args.kind,'conversion');const s={...args,id:'conv'};sounds.push(s);result=s;}
  if(op==='svc_create_version'){assert.equal(args.soundId,'conv');assert.equal(args.voiceId,'other');assert.equal(args.sourceJobId,'job-1');pitchRequests.push(args);if(pitchRequests.length<=2){await route.fulfill({status:503,json:{message:'模拟提交中断，请重试'}});return;}reused++;result=add('job-reused','other',args.pitchShiftSemitones);}
  if(op==='studio_update_version'){const v=versions.find(v=>v.id===args.versionId);if(args.final!==undefined)sounds.find(s=>s.id===v.soundId).finalVersionId=args.final?v.id:undefined;if(args.kept!==undefined)v.kept=args.kept;if(args.deleted!==undefined)v.deleted=args.deleted;result=v;}
  if(op==='studio_update_sound'){const item=sounds.find(s=>s.id===args.soundId);Object.assign(item,args);result=item;}
  if(op==='studio_cancel'){const v=versions.find(v=>v.id===args.versionId);Object.assign(v,{state:'cancelled',stage:'已取消'});result=v;}
  assert.notEqual(op,'studio_generate','conversion must not use text generation');await route.fulfill({json:result});
 });
 await page.route('**/conversion/upload?*',async route=>{const query=new URL(route.request().url()).searchParams;assert.equal(query.get('soundId'),'conv');assert.equal(query.get('voiceId'),'gong');assert.equal(query.get('pitchShiftSemitones'),uploads===0?'3':'0');assert.deepEqual(route.request().postDataBuffer(),wav);uploads++;if(uploads===1){await route.fulfill({status:503,json:{message:'模拟上传中断'}});return;}await route.fulfill({json:add('job-1')});});
 await page.route('**/conversion/audio/**',route=>route.fulfill({contentType:'audio/wav',body:wav}));
 try{
  await page.goto(server.resolvedUrls.local[0]);await page.locator('[data-action="new-sound"]').click();await page.locator('[name="kind"][value="conversion"]').check();await page.fill('#sound-title','歌声音色');await page.locator('#sound-form button').click();
  assert.equal(await page.locator('.sidebar a[href="./conversion.html"]').count(),0);assert.equal(await page.locator('#creation-text').count(),0);
  assert.equal(await page.getByLabel('整体升降调',{exact:true}).inputValue(),'0');
  await page.getByLabel('原始音频', {exact:true}).setInputFiles({name:'完整歌曲.wav',mimeType:'audio/wav',buffer:wav});await page.getByLabel('目标音色',{exact:true}).selectOption('gong');await page.getByLabel('整体升降调',{exact:true}).selectOption('3');await mkdir('test-results/studio-conversion',{recursive:true});await page.screenshot({path:'test-results/studio-conversion/pitch-compose.png'});await page.getByRole('button',{name:'转换为新版本',exact:true}).click();await page.getByText('模拟上传中断',{exact:true}).waitFor();await page.getByLabel('整体升降调',{exact:true}).selectOption('0');await page.getByRole('button',{name:'转换为新版本',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#version-audio')?.readyState>=2);assert.equal(uploads,2);
  await page.locator('[data-action="final"]').click();await page.locator('[data-action="keep"]').click();assert.equal(sounds[1].finalVersionId,'job-1');assert.equal(versions[0].kept,true);
  await page.locator('[data-action="iterate"]').click();await page.getByLabel('目标音色',{exact:true}).selectOption('other');await page.getByLabel('整体升降调',{exact:true}).selectOption('3');await page.getByRole('button',{name:'转换为新版本',exact:true}).click();await page.getByText('模拟提交中断，请重试',{exact:true}).waitFor();await page.getByLabel('整体升降调',{exact:true}).selectOption('-2');await page.getByRole('button',{name:'转换为新版本',exact:true}).click();await page.waitForFunction(()=>!document.body.classList.contains('busy'));await page.getByRole('button',{name:'转换为新版本',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#version-audio')?.dataset.version==='job-reused');assert.equal(reused,1);assert.equal(uploads,2);assert.deepEqual(pitchRequests.map(r=>r.pitchShiftSemitones),[3,-2,-2]);assert.notEqual(pitchRequests[0].requestId,pitchRequests[1].requestId);assert.equal(pitchRequests[1].requestId,pitchRequests[2].requestId);await page.locator('.version-row').filter({hasText:'降 2 半音'}).waitFor();await page.locator('[data-action="iterate"]').click();assert.equal(await page.getByLabel('整体升降调',{exact:true}).inputValue(),'-2');await page.getByLabel('整体升降调',{exact:true}).selectOption('4');await page.click('[data-action="close"]');await page.locator('[data-action="compose"]').click();assert.equal(await page.getByLabel('整体升降调',{exact:true}).inputValue(),'4');await page.click('[data-action="close"]');
  for(let i=0;i<21;i++)add(`history-${i}`);await page.reload();await page.getByText('第 1 / 3 页 · 共 23 条',{exact:true}).waitFor();assert.equal(await page.locator('.version-row').count(),10);const rowGeometry=await page.locator('.version-row').first().evaluate(row=>{const voice=row.querySelector('.version-metadata').getBoundingClientRect(),description=row.querySelector('.version-description').getBoundingClientRect();return {height:row.getBoundingClientRect().height,voiceCenter:voice.y+voice.height/2,descriptionCenter:description.y+description.height/2};});assert.ok(rowGeometry.height<=56,JSON.stringify(rowGeometry));assert.ok(Math.abs(rowGeometry.voiceCenter-rowGeometry.descriptionCenter)<2,JSON.stringify(rowGeometry));
  await page.waitForFunction(()=>document.querySelector('#version-audio')?.readyState>=2);await page.locator('#version-audio').evaluate(a=>{a.dataset.probe='retained';a.loop=true;return a.play();});await page.getByRole('button',{name:'下一页',exact:true}).click();await page.getByText('第 2 / 3 页 · 共 23 条',{exact:true}).waitFor();await page.waitForTimeout(2100);assert.equal(await page.locator('#version-audio').getAttribute('data-probe'),'retained');assert.equal(pages.at(-1).conversionPage,2);
  await page.getByRole('button',{name:'下一页',exact:true}).click();await page.getByText('第 3 / 3 页 · 共 23 条',{exact:true}).waitFor();assert.equal(await page.locator('.version-row').count(),3);
  await page.locator('.more-menu summary').click();await page.getByRole('button',{name:'试听原音',exact:true}).click();await page.locator('dialog audio').waitFor();await page.click('[data-action="close"]');await page.locator('.more-menu summary').click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载转换人声',exact:true}).click();assert.match((await download).suggestedFilename(),/人声.*wav/);
  await mkdir('test-results/studio-conversion',{recursive:true});await page.screenshot({path:'test-results/studio-conversion/desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('.version-row').first().evaluate(row=>row.getBoundingClientRect().height)<=68);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-results/studio-conversion/mobile.png',fullPage:true});assert.deepEqual(errors,[]);
  await page.setViewportSize({width:1440,height:1000});await page.locator('.more-menu summary').click();await page.locator('[data-action="delete"]').click();await page.waitForFunction(()=>document.querySelector('#version-audio')?.dataset.version==='job-1');assert.equal(versions.find(v=>v.id==='job-reused').deleted,true);
  await page.locator('.entity-menu[data-entity-kind="sound"] summary').click();await page.locator('[data-action="delete-entity"][data-kind="sound"]').click();await page.locator('[data-action="confirm-delete"]').click();await page.waitForFunction(()=>document.querySelectorAll('.sound-tab').length===1);assert.equal(pages.at(-1).conversionSoundId,undefined);assert.equal(sounds[1].deleted,true);
 }catch(e){console.log(await page.locator('#toast').textContent());throw e;}finally{await browser.close();await server.close();}
});

test('speech compose stays compact with both reference players and an accessible submit on desktop and phone',async()=>{
 const wav=Buffer.from(encodeWav([Float32Array.from({length:24000*3},(_,i)=>Math.sin(i*.1)*.2)],24000));
 const server=await createServer({server:{port:0,host:'127.0.0.1'},plugins:[{name:'bootstrap',transformIndexHtml(html){return html.replace('</head>','<script id="music-room-service" type="application/json">{"token":"test-token","url":"/","workspace":"compact-compose-test"}</script></head>');}}]});await server.listen();
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']}),page=await browser.newPage({viewport:{width:1440,height:1000}});
 await page.route('**/api/studio_library',r=>r.fulfill({json:{projects:[{id:'p',title:'短片'}],sounds:[{id:'s',projectId:'p',kind:'speech',title:'旁白'}],versions:[],voices:[{id:'voice',name:'我的声音',duration:3,processing:{state:'succeeded'}}],conversionVoices:[],engines:{speech:{canGenerate:true,logs:[]},music:{canGenerate:false,logs:[]},conversion:{ready:true,message:'音色转换已就绪',model:'Seed-VC · F16 · v1_svc',backend:'Metal',separationModel:'HTDemucs · F16',directory:'/models/conversion'}}}}));
 await page.route('**/speech/voice-audio/**',r=>r.fulfill({contentType:'audio/wav',body:wav}));
 try{await page.goto(server.resolvedUrls.local[0]);await page.locator('[data-action="compose"]').first().click();await page.waitForFunction(()=>[...document.querySelectorAll('#voice-preview audio')].length===2&&[...document.querySelectorAll('#voice-preview audio')].every(a=>a.readyState>=2));
  for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);const backdrop=await page.locator('dialog').evaluate(el=>{const s=getComputedStyle(el,'::backdrop');return {color:s.backgroundColor,filter:s.backdropFilter};});assert.equal(backdrop.color,'rgba(8, 12, 9, 0.72)');assert.equal(backdrop.filter,'none');}await page.evaluate(()=>document.documentElement.dataset.theme='light');
  assert.equal(await page.locator('#creation-text').getAttribute('rows'),'2');assert.equal(await page.locator('#creation-text').evaluate(e=>getComputedStyle(e).resize),'vertical');assert.ok(await page.locator('.reference-upload').evaluate(e=>e.getBoundingClientRect().height)<45);
  for(const width of [1440,390]){await page.setViewportSize({width,height:844});const geometry=await page.locator('#compose-form').evaluate(form=>{const voice=form.querySelector('#voice'),upload=form.querySelector('.reference-upload'),summary=upload.querySelector('summary'),group=upload.closest('.form-group');return {selectHeight:voice.getBoundingClientRect().height,summaryHeight:summary.getBoundingClientRect().height,bottomGap:group.getBoundingClientRect().bottom-upload.getBoundingClientRect().bottom,uploadMarginTop:parseFloat(getComputedStyle(upload).marginTop),uploadMarginBottom:parseFloat(getComputedStyle(upload).marginBottom)};});assert.equal(geometry.selectHeight,36);assert.ok(geometry.summaryHeight>=32&&geometry.summaryHeight<=36);assert.ok(geometry.bottomGap<=12);assert.ok(geometry.uploadMarginTop<=4&&geometry.uploadMarginBottom===0);for(const a of await page.locator('#voice-preview audio').all()){assert.equal(await a.evaluate(a=>a.getBoundingClientRect().height),32);await a.evaluate(a=>a.play());assert.equal(await a.evaluate(a=>a.paused),false);}await page.fill('#creation-text','这是完整的测试朗读。');assert.equal(await page.locator('#generate').isEnabled(),true);await page.locator('#generate').scrollIntoViewIfNeeded();assert.ok(await page.locator('#generate').evaluate(e=>{const r=e.getBoundingClientRect();return r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth;}));await mkdir('test-results/studio-conversion',{recursive:true});await page.screenshot({path:`test-results/studio-conversion/compact-speech-${width}.png`});}
  await page.click('[data-action="close"]');await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByText('音色转换 · Seed-VC',{exact:true}).waitFor();assert.equal(await page.locator('#conversion-status').textContent(),'音色转换已就绪');assert.match(await page.locator('#conversion-models').textContent(),/Seed-VC.*F16.*v1_svc.*Metal.*HTDemucs/);assert.equal(await page.locator('#conversion-directory').textContent(),'/models/conversion');
 }finally{await browser.close();await server.close();}
});
