import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,mkdir,writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {MusicService} from '../src/service/service.ts';
import {processRenderer} from '../src/service/render/process.ts';
import {serveHttp} from '../src/server/http.ts';
const root=await mkdtemp(join(tmpdir(),'music-ui-')),out=resolve('test-results/service');await mkdir(out,{recursive:true});
const service=await MusicService.open(root,processRenderer(),p=>readFile(resolve('dist',p)));
const http=await serveHttp(service,{read:p=>readFile(resolve('dist',p)),has:p=>existsSync(resolve('dist',p)),embedded:false});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const client=new Client({name:'browser-agent',version:'1'});
await client.connect(new StreamableHTTPClientTransport(new URL(http.runtime.url+'/mcp'),{requestInit:{headers:{authorization:`Bearer ${http.runtime.token}`}}}));
const tool=async(name,args={})=>{const r=await client.callTool({name,arguments:args});assert.ok(!r.isError,JSON.stringify(r));return JSON.parse(r.content[0].text);};
try {
  await page.goto(http.runtime.url);await page.locator('#service-state').filter({hasText:'已连接'}).waitFor();
  assert.equal(await page.locator('#finished-audio').isVisible(),false);
  const doc=JSON.parse(await readFile('src/music/authoring/example.json','utf8'));
  await tool('import_revision',{compositionJson:JSON.stringify(doc)});
  await page.locator('[data-song="window-study-v1"]').waitFor({state:'attached'});await page.locator('.work-group').filter({has:page.locator('[data-song="window-study-v1"]')}).locator('summary').click();await page.locator('[data-song="window-study-v1"]').click();
  assert.equal(await page.locator('#song-title').textContent(),doc.work.title);
  await page.click('#export');
  const ready=page.locator('#service-jobs button').filter({hasText:'试听后台 WAV'}).first();await ready.waitFor({timeout:15000});await ready.click();
  await page.waitForFunction(()=>document.querySelector('#service-audio audio')?.currentTime>.05);
  const audio=await page.$eval('#service-audio audio',a=>({duration:a.duration,time:a.currentTime}));assert.equal(audio.duration,20);
  await page.click('#play');await page.waitForFunction(()=>window.musicRoom.engine.playing);assert.equal(await page.$eval('#service-audio audio',a=>a.paused),true);await page.click('#play');
  await page.fill('#service-feedback','保留主题，第二版减少鼓。');await page.click('#service-save-feedback');await page.locator('#service-feedback-list').filter({hasText:'保留主题'}).waitFor();
  await page.reload();await page.locator('#service-state').filter({hasText:'已连接'}).waitFor();assert.equal(await page.locator('#song-title').textContent(),doc.work.title);
  const x=structuredClone(doc);x.revision={...x.revision,id:'window-study-v2',label:'扩写答句'};
  await page.locator('.service-tools summary').click();await page.check('#service-parent');
  await page.locator('#import-file').setInputFiles({name:'answer.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(x))});
  await page.waitForFunction(()=>window.musicRoom.songId==='window-study-v2');
  assert.equal((await tool('get_revision',{projectId:doc.work.id,revisionId:x.revision.id})).metadata.parentId,doc.revision.id);
  assert.ok(!(await page.evaluate(()=>Object.keys(localStorage))).includes('music-room-imports-v1'));
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(out,'mobile.png'),fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile overflow');
  await page.setViewportSize({width:1400,height:1000});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await page.locator('.topbar').count(),1);await page.screenshot({path:join(out,'desktop.png')});await page.locator('.service-panel').screenshot({path:join(out,'tasks.png')});
  assert.deepEqual(errors,[]);await writeFile(join(out,'verification.json'),JSON.stringify({checks:10,audio,parent:doc.revision.id,errors},null,2));
  console.log('Service browser verified: agent version discovery, actual backend audio, persisted feedback, refresh, parent import, no browser storage, mobile.');
} finally {await client.close();await browser.close();await service.jobs.close();await http.close();await service.store.close();await rm(root,{recursive:true,force:true});}
