import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,mkdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {chromium} from 'playwright';
import {MusicService} from '../src/service/service.ts';
import {serveHttp} from '../src/server/http.ts';
import {encodeWav} from '../src/wav.ts';
import {testResources} from '../src/service/resources/testing.ts';

const unused={unsupported:()=>undefined,installed:()=>false,chooseDirectory:async()=>undefined,prepare:async()=>{},launch:async()=>{throw Error('unused');}};
test('MIDI tools belong to one sound; legacy links enter its version without a second library',async()=>{
 const root=await mkdtemp(join(tmpdir(),'score-context-')),read=p=>readFile(resolve('dist',p));
 let renderGate=Promise.resolve(),releaseRender=()=>{};
 const renderer=({composition})=>({result:renderGate.then(()=>({wav:new Uint8Array(encodeWav([new Float32Array(Math.round(composition.score.duration*44100)),new Float32Array(Math.round(composition.score.duration*44100))],44100)),peak:0,rms:0,attenuation:1,engine:'test'})),cancel:()=>{}});
 const service=await MusicService.open(root,renderer,read,false,unused,undefined,undefined,testResources());
 const http=await serveHttp(service,{read,has:p=>existsSync(resolve('dist',p)),embedded:false});
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(7000);
 await page.addInitScript(()=>{const Original=window.AudioContext;window.testAudioContexts=[];window.AudioContext=class extends Original{constructor(...args){super(...args);window.testAudioContexts.push(this);}};});
 try{
  await service.call('create_project',{projectId:'film',title:'短片项目'});
  const s=await service.call('studio_create_sound',{projectId:'film',title:'开场旋律',kind:'clip'});
  const other=await service.call('studio_create_sound',{projectId:'film',title:'片尾旋律',kind:'clip'});
  const compositionJson=await readFile('src/music/authoring/example.json','utf8');
  const v1=await service.call('studio_import_score',{soundId:s.id,compositionJson});
  const v2=await service.call('studio_import_score',{soundId:s.id,compositionJson,parentId:v1.id});
  await service.call('studio_import_score',{soundId:other.id,compositionJson});
  await page.goto(http.runtime.url+'/score.html#'+v1.source.id);
  await page.waitForURL(url=>url.pathname==='/');
  await page.locator('[data-action="score-tools"]').waitFor({state:'attached'});
  assert.equal(await page.locator('.version-row.selected [data-id]').getAttribute('data-id'),v1.id);
  assert.equal(await page.locator('a[href*="score.html"]').count(),0);
  assert.equal(await page.locator('#library').count(),0);
  renderGate=new Promise(resolve=>releaseRender=resolve);await page.click('[data-action="render"]');
  await page.locator('.more-menu summary').click();await page.click('[data-action="score-tools"]');
  await page.locator('#score-tools-host #overview').waitFor();
  assert.match(await page.locator('#dialog-title').innerText(),/短片项目.*开场旋律.*V1/);
  assert.equal(await page.locator('#compare-target option').count(),1,'only sibling versions may be compared');
  assert.equal(await page.locator('#library').count(),0,'no nested old navigation');
  await page.click('#select-view');await page.click('#loop');
  assert.equal(await page.locator('#loop').getAttribute('aria-pressed'),'true');
  await page.click('#mixer summary');await page.locator('.mute').first().click();
  assert.equal(await page.locator('.mute').first().getAttribute('aria-pressed'),'true');
  await page.click('#compare-start');await page.click('#compare-b');
  assert.match(await page.locator('#dialog-title').innerText(),/V2/);
  await page.click('#compare-exit');
  assert.match(await page.locator('#dialog-title').innerText(),/V1/);
  assert.equal(await page.locator('.mute').first().getAttribute('aria-pressed'),'true','comparison restores the original mix');
  assert.equal(await page.locator('#loop').getAttribute('aria-pressed'),'true','comparison restores the selected loop');
  await page.fill('#score-feedback','开头保留四小节，后面再变化');await page.click('#save-score-feedback');
  await page.locator('#status').filter({hasText:'听评已保存'}).waitFor();
  const feedback=(await service.call('get_project',{projectId:'film'})).feedback;
  assert.equal(feedback.length,1);assert.equal(feedback[0].revisionId,v1.source.id);assert.deepEqual(feedback[0].range,{start:0,end:10});
  const midi=page.waitForEvent('download');await page.click('#midi');assert.match((await midi).suggestedFilename(),/\.mid$/);
  await page.click('#play');await page.locator('#play').filter({hasText:'暂停'}).waitFor();
  releaseRender();await page.waitForFunction(()=>!!document.querySelector('#version-audio')?.src);
  assert.equal(await page.locator('#version-audio').evaluate(a=>a.paused),true,'background rendering cannot start a second player over MIDI playback');
  await mkdir('test-results/score-context',{recursive:true});await page.locator('.dialog-body').evaluate(el=>el.scrollTop=0);await page.screenshot({path:'test-results/score-context/desktop.png',fullPage:true});
  for(const width of [1024,768,390]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth));}
  await page.screenshot({path:'test-results/score-context/mobile.png',fullPage:true});
  await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').evaluate(d=>d.open),false);
  await page.waitForFunction(()=>window.testAudioContexts.length>0&&window.testAudioContexts.every(c=>c.state==='closed'));
  await page.setViewportSize({width:1440,height:1000});
  await page.locator(`[data-action="version"][data-id="${v2.id}"]`).click();
  await page.locator('.more-menu summary').click();await page.click('[data-action="score-tools"]');
  await page.locator('#dialog-title').filter({hasText:'V2'}).waitFor();
  assert.equal(await page.locator('#loop').getAttribute('aria-pressed'),'false');
  assert.equal(await page.locator('.mute').first().getAttribute('aria-pressed'),'false');
  await page.click('#mixer summary');await page.selectOption('#lead','flute');await page.click('#save-mix');
  await page.waitForFunction(()=>document.querySelectorAll('.version-row').length===3&&!document.querySelector('dialog').open);
  const library=await service.call('studio_library',{}),child=library.versions.find(v=>v.parentId===v2.id);
  assert.ok(child);assert.equal(child.soundId,s.id);assert.equal(child.scoreMix.lead,'flute');
  assert.equal(library.sounds.length,2);assert.equal(library.versions.filter(v=>v.soundId===other.id).length,1);
  await page.reload();await page.locator(`#version-audio[data-version="${child.id}"]`).waitFor();
  await page.locator('.more-menu summary').click();await page.click('[data-action="score-tools"]');await page.locator('#lead').waitFor({state:'attached'});
  assert.equal(await page.inputValue('#lead'),'flute','saved mix is restored when reopening its version');
  await page.click('[data-action="close"]');
  await page.goto(http.runtime.url+'/score.html#missing-revision');await page.waitForURL(url=>url.pathname==='/');
  await page.locator('#toast').filter({hasText:'不存在或已删除'}).waitFor();
  assert.equal(await page.locator('#score-tools-host').count(),0);

  assert.deepEqual(errors,[]);
 }catch(e){console.log('Score UI failure:',await page.locator('#status').allTextContents(),await page.locator('#toast').allTextContents(),errors);throw e;}finally{releaseRender();await browser.close();await http.close();await service.close();await rm(root,{recursive:true,force:true});}
});
