import { chromium } from 'playwright';
import { mkdir, readFile, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { scoreToMidi } from '../src/midi.ts';
import { validateComposition } from '../src/music/authoring/validate.mjs';
const root=new URL('../',import.meta.url);
const example=JSON.parse(await readFile(new URL('src/music/authoring/example.json',root),'utf8'));
const output=new URL('test-results/imports/',root); await mkdir(output,{recursive:true});
const isolated=await mkdtemp(path.join(tmpdir(),'music-authoring-'));
try {
  execFileSync('unzip',['-q',new URL('public/music-authoring-kit.zip',root).pathname,'-d',isolated]);
  const result=execFileSync(process.execPath,['check.mjs','example.json'],{cwd:isolated,encoding:'utf8'});
  assert.match(result,/通过/);
  await writeFile(path.join(isolated,'invalid.json'),'{');
  assert.throws(()=>execFileSync(process.execPath,['check.mjs','invalid.json'],{cwd:isolated,stdio:'pipe'}));
} finally { await rm(isolated,{recursive:true,force:true}); }
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const checks=['isolated kit validates without project or packages','CLI rejects invalid JSON'],errors=[];
try {
  const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
  await context.grantPermissions(['clipboard-read','clipboard-write']);
  const page=await context.newPage(); page.on('pageerror',e=>errors.push(e.message));
  const url=process.env.MUSIC_ROOM_URL || 'http://127.0.0.1:5173';
  await page.goto(`${url}/#rain-letter-v2`); await page.waitForFunction(()=>!!window.musicRoom);
  const upload=async doc=>page.locator('#import-file').setInputFiles({name:'song.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});
  const drop=async documents=>page.evaluate(documents=> {
    const data=new DataTransfer();for(const doc of documents)data.items.add(new File([JSON.stringify(doc)],'song.json',{type:'application/json'}));
    const zone=document.querySelector('#import-drop');
    zone.dispatchEvent(new DragEvent('dragenter',{bubbles:true,dataTransfer:data}));
    const highlighted=zone.classList.contains('drag-over');
    zone.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));
    return {highlighted,cleared:!zone.classList.contains('drag-over')};
  },documents);
  assert.deepEqual(await drop([example]),{highlighted:true,cleared:true});
  await page.waitForFunction(()=>window.musicRoom.songId==='window-study-v1');
  await drop([example,example]);await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('一次拖入一个'));
  assert.equal(await page.locator('[data-song]').count(),3);
  checks.push('file drop highlights, imports and clears; multiple-file drop rejected');
  assert.equal(await page.locator('.work-group').count(),2);
  assert.equal(await page.locator('#finished-audio').isVisible(),false);
  await page.locator('#play').click(); await page.waitForFunction(()=>window.musicRoom.engine.playing);
  const rms=await page.evaluate(async()=> {
    const engine=window.musicRoom.engine, chunks=[];
    const source=`class ImportCapture extends AudioWorkletProcessor { process(inputs) { this.port.postMessage(inputs[0]?.[0]?.slice() ?? new Float32Array(128)); return true; } } registerProcessor('import-capture',ImportCapture);`;
    const sourceUrl=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));
    await engine.context.audioWorklet.addModule(sourceUrl);URL.revokeObjectURL(sourceUrl);
    const recorder=new AudioWorkletNode(engine.context,'import-capture');
    const silent=engine.context.createGain();silent.gain.value=0;
    recorder.port.onmessage=e=>chunks.push(e.data);
    engine.output.connect(recorder).connect(silent).connect(engine.context.destination);
    await new Promise(r=>setTimeout(r,1000));
    engine.output.disconnect(recorder);recorder.disconnect();silent.disconnect();
    let power=0,frames=0;for(const chunk of chunks)for(const x of chunk){power+=x*x;frames++;}
    return frames ? Math.sqrt(power/frames) : 0;
  });
  assert.ok(rms>.0001,`import playback must produce sound: ${rms}`);
  await upload({...example,score:{...example.score,bpm:0}});
  await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('score.bpm'));
  assert.equal(await page.evaluate(()=>window.musicRoom.songId),'window-study-v1');
  assert.equal(await page.evaluate(()=>window.musicRoom.engine.playing),true);
  await upload(example); await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('已存在'));
  assert.equal(await page.locator('[data-song]').count(),3);
  await page.locator('#play').click();
  const second={...example,revision:{...example.revision,id:'window-study-v2',label:'示例第二版'}};
  await upload(second); await page.waitForFunction(()=>window.musicRoom.songId==='window-study-v2');
  assert.equal(await page.locator('.work-group').count(),2); assert.equal(await page.locator('[data-song]').count(),4);
  await page.locator('#compare-start').click(); await page.locator('#compare-b').click();
  assert.equal(await page.evaluate(()=>window.musicRoom.songId),'window-study-v1');
  await page.locator('#compare-exit').click();
  assert.equal(await page.evaluate(()=>window.musicRoom.songId),'window-study-v2');
  await page.reload(); await page.waitForFunction(()=>window.musicRoom.songId==='window-study-v2');
  assert.equal(await page.evaluate(()=>window.musicRoom.engine.playing),false);
  await page.goBack(); await page.waitForFunction(()=>window.musicRoom.songId==='window-study-v1');
  await page.goForward(); await page.waitForFunction(()=>window.musicRoom.songId==='window-study-v2');
  const jsonEvent=page.waitForEvent('download'); await page.locator('#score-download').click();
  const jsonDownload=await jsonEvent; await jsonDownload.saveAs(new URL('roundtrip.json',output).pathname);
  assert.deepEqual(validateComposition(await readFile(new URL('roundtrip.json',output),'utf8')),second);
  const midiEvent=page.waitForEvent('download');await page.locator('#midi').click();
  const midiDownload=await midiEvent; assert.equal(midiDownload.suggestedFilename(),'window-study-v2.mid');
  await midiDownload.saveAs(new URL('roundtrip.mid',output).pathname);
  const wavEvent=page.waitForEvent('download',{timeout:60000});await page.locator('#export').click();
  const wavDownload=await wavEvent;await wavDownload.saveAs(new URL('roundtrip.wav',output).pathname);
  const wav=await readFile(new URL('roundtrip.wav',output)); assert.equal(wav.length,20*44100*4+44);
  let peak=0;for(let i=44;i<wav.length;i+=2)peak=Math.max(peak,Math.abs(wav.readInt16LE(i)));assert.ok(peak>100);
  await page.locator('#remove-import').click();
  assert.equal(await page.evaluate(()=>window.musicRoom.songId),'window-study-v1');
  await page.locator('#remove-import').click();
  assert.equal(await page.evaluate(()=>window.musicRoom.songId),'rain-letter-v1');
  assert.equal(await page.locator('.work-group').count(),1);
  await page.locator('#import-file').setInputFiles(new URL('roundtrip.json',output).pathname);
  await page.waitForFunction(()=>window.musicRoom.songId==='window-study-v2');
  checks.push('audible JSON playback','invalid import leaves current playing score intact','duplicate rejected','same work versions and A/B','refresh paused, back/forward','JSON exact round-trip','local MIDI and audible full WAV export','remove and recover from downloaded backup');
  await page.locator('#import-file').setInputFiles({name:'midi-study.mid',mimeType:'audio/midi',buffer:Buffer.from(scoreToMidi(example.score,'Study'))});
  await page.waitForFunction(()=>window.musicRoom.songId.startsWith('midi-'));
  assert.equal(await page.locator('#song-title').textContent(),'midi-study');
  assert.equal(await page.evaluate(()=>window.musicRoom.score.notes.length),example.score.notes.length);
  assert.match(await page.locator('#status').textContent(),/踏板/);
  const midiId=await page.evaluate(()=>window.musicRoom.songId);
  await page.reload();await page.waitForFunction(id=>window.musicRoom.songId===id,midiId);
  checks.push('standard MIDI import and refresh');
  const expanded={...example,revision:{...example.revision,id:'window-study-v3',label:'扩写版'},score:{...example.score,duration:30,sections:[...example.score.sections,{name:'新段落',subtitle:'扩写回归夹具',startBar:8,bars:4,color:'#a8cbc4'}],bars:[...example.score.bars,...Array.from({length:4},()=>({chord:'Dm',section:1}))]}};
  await upload(expanded);await page.waitForFunction(()=>window.musicRoom.songId==='window-study-v3');
  assert.equal(await page.locator('.work-group').count(),3);
  assert.equal(await page.locator('#total-duration').textContent(),'00:30');
  await page.locator('#compare-start').click();await page.locator('#compare-b').click();
  assert.equal(await page.evaluate(()=>window.musicRoom.score.bars.length),8);
  await page.locator('#compare-exit').click();
  assert.equal(await page.evaluate(()=>window.musicRoom.score.bars.length),12);
  await page.locator('.authoring-tools summary').click();
  await page.locator('#authoring-stage').selectOption('four');assert.match(await page.locator('#authoring-prompt').inputValue(),/4 小节/);
  await page.locator('#authoring-stage').selectOption('expand');
  const expansionPrompt=await page.locator('#authoring-prompt').inputValue();
  assert.ok(expansionPrompt.includes('window-study-v3.json'));assert.ok(expansionPrompt.includes('window-study'));
  const sourceEvent=page.waitForEvent('download');await page.locator('#authoring-current').click();
  assert.equal((await sourceEvent).suggestedFilename(),'window-study-v3.json');
  await page.locator('.authoring-tools summary').click();
  checks.push('short phrase grows into longer version in same project, matched phrase A/B','4/8-bar and current-project expansion prompts');
  const malicious={...example,work:{id:'markup-test',title:'<img src=x onerror="window.INJECTED=1">'},revision:{...example.revision,id:'markup-test-v1',label:'<b>version</b>'},score:{...example.score,title:'<img src=x onerror="window.INJECTED=1">',sections:[{...example.score.sections[0],name:'<img src=x onerror="window.INJECTED=1">'}],bars:example.score.bars.map(b=>({...b,chord:'<img src=x onerror="window.INJECTED=1">'}))}};
  await upload(malicious);await page.waitForFunction(()=>window.musicRoom.songId==='markup-test-v1');
  assert.equal(await page.evaluate(()=>window.INJECTED),undefined);
  assert.equal(await page.locator('#library-works img, #chords img, .sections img').count(),0);
  await page.reload(); await page.waitForFunction(()=>window.musicRoom.songId==='markup-test-v1');
  assert.equal(await page.locator('img').count(),0);
  checks.push('imported text cannot execute HTML, including reload');
  await page.locator('.authoring-tools summary').click();
  await page.locator('#authoring-prompt').fill('请按创作包写一个有明确主题的曲子。');
  await page.locator('#copy-prompt').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'请按创作包写一个有明确主题的曲子。');
  const kitEvent=page.waitForEvent('download');await page.getByRole('link',{name:'下载独立创作包 ZIP'}).click();
  assert.equal((await kitEvent).suggestedFilename(),'music-authoring-kit.zip');
  await page.screenshot({path:new URL('desktop.png',output).pathname,fullPage:true});
  await page.setViewportSize({width:390,height:844}); await page.locator('#library-toggle').click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:new URL('mobile.png',output).pathname,fullPage:true});
  checks.push('editable prompt copies, kit downloads','390px import controls');
  // Storage failure must not add a phantom version or stop the selected song.
  await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new Error('QuotaExceededError');};});
  await upload({...example,work:{id:'quota-test',title:example.work.title},revision:{...example.revision,id:'quota-test-v1'}});
  await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('本机保存失败'));
  assert.equal(await page.evaluate(()=>window.musicRoom.songId),'markup-test-v1');
  assert.equal(await page.locator('[data-song="quota-test-v1"]').count(),0);
  checks.push('storage failure is transactional');
  assert.deepEqual(errors,[]);
  await writeFile(new URL('verification.json',output),JSON.stringify({checks,rms,wavPeak:peak,errors},null,2));
  console.log(JSON.stringify({checks,rms,wavPeak:peak,errors}));
} finally {await browser.close();}
