// Generated by scripts/build-native-tts.mjs; source and patch are SHA-256 pinned.
export const nativeProgramManifest = {
  "version": "0.9.1-music-room-tail2",
  "asset": "tts-native/audio-cpp-v0.9.1-tail2-macos-arm64.tar.gz",
  "sourceUrl": "https://github.com/0xShug0/audio.cpp/archive/refs/tags/v0.9.1.tar.gz",
  "sourceSha256": "20f589b7f891eee1e9d35d1fcea5382c925cf3413f4db5ba71d70cd9a991c938",
  "patchSha256": "122bc698ff5d83201dfc3cbb1b04f689063e3bc9432bed5168fb6584c1627da4",
  "programSha256": "1a95c9eea19b062b1a19c71d14a63d8d8804760baceb3db03bc2b8ebf7846765",
  "referenceEmotionStrength": "calm-reference-blend-opt-in",
  "tailContextFrames": 32,
  "retainedTailFrames": 12,
  "vocoderContextFrames": 20,
  "fadeMs": 20,
  "finalSilenceMs": 100,
  "archiveSha256": "dfb8bc3a9d409757cc36a3cad9fa7686a2e1909fe9617aadfa11ee7b268a7d01",
  "archiveBytes": 6603864
} as const;
