// Generated by scripts/build-native-tts.mjs; source and patch are SHA-256 pinned.
export const nativeProgramManifest = {
  "version": "0.9.1-music-room-tail1",
  "asset": "tts-native/audio-cpp-v0.9.1-tail1-macos-arm64.tar.gz",
  "sourceUrl": "https://github.com/0xShug0/audio.cpp/archive/refs/tags/v0.9.1.tar.gz",
  "sourceSha256": "20f589b7f891eee1e9d35d1fcea5382c925cf3413f4db5ba71d70cd9a991c938",
  "patchSha256": "10bf1eb6a0924bea335a4689aaa2a7ce3075e81d61a1ddd39dd532071e645998",
  "programSha256": "0a7c26054f56b6577733bddbf3c6f0979174a49fcca7542794af75c16b45cee9",
  "tailContextFrames": 32,
  "retainedTailFrames": 12,
  "vocoderContextFrames": 20,
  "fadeMs": 20,
  "finalSilenceMs": 100,
  "archiveSha256": "e6696a57582affe10c1581f91a1ea7450fd68138fa92d7df157672b95d70b07c",
  "archiveBytes": 6601179
} as const;
