import {referenceIdentity} from '../resources/profiles.ts';
import {ownedCommand} from '../resources/commands.ts';
import {createReadStream} from 'node:fs';
import {open} from 'node:fs/promises';
import {checkDisk,diskGuard} from '../resources/installation.ts';
import {spawn} from 'node:child_process';
import {existsSync,lstatSync,mkdirSync,readFileSync,writeFileSync,readdirSync,renameSync,copyFileSync,chmodSync,openSync,closeSync,unlinkSync,realpathSync} from 'node:fs';
import {isAbsolute,join,dirname} from 'node:path';
import {homedir} from 'node:os';
import {createHash,randomUUID} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {wavInfo,type SpeechDriver,type SpeechContext} from './speech.ts';
import type {SpeechTask} from './supervisor.ts';
import {modelRevision} from './python.ts';
import {referenceRequirements} from './reference-requirements.ts';
import type {AssetReader} from '../render/renderer.ts';
import {readBuiltinVoices,prepareBuiltinConditioning} from './presets.ts';
export const sourceRevision='830f6f8f94a51fea23ab1d639027a86200075a4e';
const sourceHash='cc7a7c65a39ecb4cb6befa125957764eb35efd38c28123abbb1cc136390a39dd';
const uvUrl='https://github.com/astral-sh/uv/releases/download/0.12.23/uv-aarch64-apple-darwin.tar.gz',uvHash='50487ae565ccd96e499056b4674d438f4c53170202617b4c759defe0c6a1b544';
const alive=(pid:number)=>{try{process.kill(pid,0);return true;}catch(e:any){return e.code!=='ESRCH';}};
export function checkedDirectory(directory:string){if(!isAbsolute(directory))throw new Error('安装目录需要绝对路径');if(existsSync(directory)&&lstatSync(directory).isSymbolicLink())throw new Error('语音安装目录不能是符号链接');mkdirSync(directory,{recursive:true,mode:0o700});const root=realpathSync(directory),marker=join(root,'.music-room-indextts.json');if(existsSync(marker)){if(lstatSync(marker).isSymbolicLink()||JSON.parse(readFileSync(marker,'utf8')).sourceRevision!==sourceRevision)throw new Error('该目录不是受管理的 IndexTTS 2.0 环境');}else{if(readdirSync(root).some(n=>n!=='.DS_Store'))throw new Error('首次安装请选择空文件夹');writeFileSync(marker,JSON.stringify({format:'music-room-indextts',version:1,sourceRevision}),{flag:'wx',mode:0o600});}for(const part of ['bin','tmp','cache'])mkdirSync(join(root,part),{recursive:true,mode:0o700});return root;}
export function lock(root:string){const path=join(root,'.music-room-indextts.lock'),owner=randomUUID();try{const fd=openSync(path,'wx',0o600);writeFileSync(fd,JSON.stringify({pid:process.pid,owner}));closeSync(fd);}catch(e:any){if(e.code!=='EEXIST')throw e;if(lstatSync(path).isSymbolicLink())throw new Error('语音环境锁不能是符号链接');const old=JSON.parse(readFileSync(path,'utf8'));if(alive(old.pid)||old.workerPid&&alive(old.workerPid))throw new Error('IndexTTS 环境正在被另一个工作台使用');const recovery=path+'.recovery',fd=openSync(recovery,'wx',0o600);try{const current=JSON.parse(readFileSync(path,'utf8'));if(current.owner!==old.owner||alive(current.pid)||current.workerPid&&alive(current.workerPid))throw new Error('语音环境正在使用');unlinkSync(path);const f=openSync(path,'wx',0o600);writeFileSync(f,JSON.stringify({pid:process.pid,owner}));closeSync(f);}finally{closeSync(fd);unlinkSync(recovery);}}return {path,owner,release:()=>{if(existsSync(path)&&JSON.parse(readFileSync(path,'utf8')).owner===owner)unlinkSync(path);}};}
export async function runCommand(command:string,args:string[],context:SpeechContext,cwd:string){await ownedCommand(command,args,cwd,context);}
async function download(url:string,path:string,expected:string,context:SpeechContext){
 context.signal.throwIfAborted();const digest=async()=>{const hash=createHash('sha256');for await(const part of createReadStream(path)){context.signal.throwIfAborted();hash.update(part);}return hash.digest('hex');};if(existsSync(path)&&await digest()===expected)return;
 const response=await fetch(url,{signal:context.signal});if(!response.ok||!response.body)throw new Error(`下载失败：HTTP ${response.status}`);const length=Number(response.headers.get('content-length'));if(Number.isSafeInteger(length)&&length>0)checkDisk(dirname(path),length);
 const partial=path+'.partial';if(existsSync(partial)&&lstatSync(partial).isSymbolicLink())throw new Error('下载暂存文件不能是符号链接');const file=await open(partial,'w',0o600),hash=createHash('sha256'),guard=diskGuard(dirname(path));
 try{for await(const bytes of response.body){context.signal.throwIfAborted();guard(bytes.length);hash.update(bytes);await file.write(bytes);}}finally{await file.close();}
 if(hash.digest('hex')!==expected)throw new Error('下载文件校验失败');context.signal.throwIfAborted();renameSync(partial,path);
}
export function speechWorker(task:SpeechTask,context:SpeechContext,command:string,args:string[],lease:{path:string;owner:string}){
 context.signal.throwIfAborted();return new Promise<void>((resolve,reject)=>{const child=spawn(command,args,{detached:!!context.lease,stdio:['pipe','pipe','pipe']});let last:string[]=[];let killed=false;let timeout:ReturnType<typeof setTimeout>|undefined;let force:ReturnType<typeof setTimeout>|undefined;let failure:Error|undefined;child.stdin.on('error',()=>{});
  child.once('error',e=>{failure=e;});
  const stop=()=>{if(killed)return;killed=true;child.stdin.end();timeout=setTimeout(()=>child.kill('SIGTERM'),7000);timeout.unref();force=setTimeout(()=>{try{if(context.lease&&child.pid)process.kill(-child.pid,'SIGKILL');else child.kill('SIGKILL');}catch{}},14000);force.unref();};context.signal.addEventListener('abort',stop,{once:true});
  for(const stream of [child.stdout,child.stderr]){let pending='';stream.on('data',c=>{pending+=c.toString();const lines=pending.split(/[\r\n]/);pending=lines.pop()??'';for(const line of lines){if(line.startsWith('MUSIC_ROOM_TTS_EVENT ')){try{const event=JSON.parse(line.slice(21));if(typeof event.stage==='string')context.stage(event.stage);}catch{}continue;}if(line.trim()){last.push(line);last=last.slice(-12);context.report(line);}}if(pending.length>4000){context.report(pending.slice(-1000));pending='';}});stream.on('end',()=>{if(pending.trim()){last.push(pending);context.report(pending);}});}
  child.once('close',code=>{if(timeout)clearTimeout(timeout);if(force)clearTimeout(force);context.signal.removeEventListener('abort',stop);if(context.signal.aborted)reject(context.signal.reason);else if(code!==0)reject(failure??new Error(last.join('\n').slice(-2000)||`IndexTTS 进程退出：${code}`));else resolve();});
  try{if(child.pid)context.trackProcess?.(child.pid);const current=JSON.parse(readFileSync(lease.path,'utf8'));if(current.owner!==lease.owner)throw new Error('语音环境锁已改变');writeFileSync(lease.path,JSON.stringify({...current,workerPid:child.pid}));child.stdin.write(JSON.stringify({...task,owner:lease.owner,resourceLease:context.lease})+'\n');}catch(error){stop();reject(error);}
 });
}
export function createPythonSpeechDriver(command=process.execPath,args=[fileURLToPath(new URL('../../server/dev.ts',import.meta.url)),'tts-worker'],read?:AssetReader):SpeechDriver{
 const installed=(root:string)=>{try{const metadata=JSON.parse(readFileSync(join(root,'installed.json'),'utf8'));return metadata.runtimeVersion===2&&metadata.pythonMinor==='3.11'&&metadata.sourceRevision===sourceRevision&&metadata.modelRevision===modelRevision&&existsSync(join(root,'.venv','bin','python'))&&['gpt.pth','s2mel.pth','qwen0.6bemo4-merge/model.safetensors','config.yaml'].every(f=>existsSync(join(root,'source','checkpoints',f)));}catch{return false;}};
 return {referenceProfile:referenceIdentity(),engineLabel:'PyTorch',installed,builtinVoices:read?()=>readBuiltinVoices(read):undefined,exampleVoice:root=>{try{const raw=readFileSync(join(root,'source','examples','voice_01.wav'));if(createHash('sha256').update(raw).digest('hex')!=='e33e6ee0107a1dd58e1d66dd90c13df3d55a8683047cc3d7ea206dad84ed3fc8')return;const bytes=readFileSync(join(root,'source','examples','voice_01-pcm.wav')),metadata=JSON.parse(readFileSync(join(root,'installed.json'),'utf8'));if(createHash('sha256').update(bytes).digest('hex')===metadata.exampleSha256)return new Uint8Array(bytes);}catch{return;}},prepare:async(directory,context)=>{const root=checkedDirectory(directory),lease=lock(root);try{if(installed(root))return;context.stage('下载 IndexTTS 2.0 程序');await download(`https://codeload.github.com/index-tts/index-tts/tar.gz/${sourceRevision}`,join(root,'source.tar.gz'),sourceHash,context);if(!existsSync(join(root,'source','uv.lock'))){await runCommand('/usr/bin/tar',['-xzf',join(root,'source.tar.gz'),'-C',root],context,root);renameSync(join(root,`index-tts-${sourceRevision}`),join(root,'source'));}
   if(!existsSync(join(root,'bin','uv'))){const existing=[join(homedir(),'.local','bin','uv'),join(homedir(),'Music','YuE2','bin','uv')].find(existsSync);if(existing){copyFileSync(existing,join(root,'bin','uv'));chmodSync(join(root,'bin','uv'),0o700);}else if(process.platform==='darwin'&&process.arch==='arm64'){await download(uvUrl,join(root,'uv.tar.gz'),uvHash,context);await runCommand('/usr/bin/tar',['-xzf',join(root,'uv.tar.gz'),'-C',root],context,root);copyFileSync(join(root,'uv-aarch64-apple-darwin','uv'),join(root,'bin','uv'));chmodSync(join(root,'bin','uv'),0o700);}else throw new Error('请先安装 uv，然后重试准备语音环境');}
   context.stage('安装专用 Python 和语音依赖');await speechWorker({directory:root,step:'dependencies'},context,command,args,lease);context.stage('下载固定的 IndexTTS 2.0 模型与语音组件');await speechWorker({directory:root,step:'models'},context,command,args,lease);context.stage('准备官方示例声音');await download(`https://media.githubusercontent.com/media/index-tts/index-tts/${sourceRevision}/examples/voice_01.wav`,join(root,'source','examples','voice_01.wav'),'e33e6ee0107a1dd58e1d66dd90c13df3d55a8683047cc3d7ea206dad84ed3fc8',context);await speechWorker({directory:root,step:'reference'},context,command,args,lease);const example=readFileSync(join(root,'source','examples','voice_01-pcm.wav'));wavInfo(example);const exampleSha256=createHash('sha256').update(example).digest('hex');writeFileSync(join(root,'installed.json'),JSON.stringify({runtimeVersion:2,pythonMinor:'3.11',sourceRevision,modelRevision,exampleSha256,installedAt:new Date().toISOString()}),{mode:0o600});context.stage('IndexTTS 2.0 已准备好');
  }finally{lease.release();}},cleanReference:async(directory,request,context)=>{
   const root=checkedDirectory(directory);const lease=lock(root);
   try{
    if(!existsSync(join(root,'bin','uv'))){await download(uvUrl,join(root,'uv.tar.gz'),uvHash,context);await runCommand('/usr/bin/tar',['-xzf',join(root,'uv.tar.gz'),'-C',root],context,root);copyFileSync(join(root,'uv-aarch64-apple-darwin','uv'),join(root,'bin','uv'));chmodSync(join(root,'bin','uv'),0o700);}
    mkdirSync(join(root,'source'),{recursive:true,mode:0o700});
    const referenceRoot=join(root,'reference-cleanup'),marker=join(referenceRoot,'installed.json'),requirementsHash=createHash('sha256').update(referenceRequirements).digest('hex');mkdirSync(referenceRoot,{recursive:true,mode:0o700});
    let ready=false;try{ready=JSON.parse(readFileSync(marker,'utf8')).requirementsHash===requirementsHash&&existsSync(join(referenceRoot,'.venv','bin','python'));}catch{}
    if(!ready){writeFileSync(join(referenceRoot,'requirements.txt'),referenceRequirements,{mode:0o600});context.stage('首次准备人声清理环境');if(!existsSync(join(referenceRoot,'.venv','bin','python')))await speechWorker({directory:root,step:'reference-venv'},context,command,args,lease);await speechWorker({directory:root,step:'reference-dependencies'},context,command,args,lease);writeFileSync(marker,JSON.stringify({requirementsHash}),{mode:0o600});}
    await speechWorker({directory:root,step:'clean-reference',referenceRequest:request},context,command,args,lease);
   }finally{lease.release();}
  },generate:async(directory,request,context)=>{const root=checkedDirectory(directory);if(!installed(root))throw new Error('语音模型未准备完成，请先准备环境');const lease=lock(root);try{const conditioning=read?await prepareBuiltinConditioning(root,readFileSync(request.referencePath),read):undefined;await speechWorker({directory:root,step:'infer',request:{...request,...conditioning}},context,command,args,lease);}finally{lease.release();}}};
}
